### ISSUE TITLE
API Automation -Intermittent Error-jSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#883] opened 2020-11-20 04:52 UTC
Description: Try to hit the same code couple times, it gives error "ERROR - jSON Parse error: Unrecognized token '<'" intermittently. Some times it get passed as well

CMD:
![image](https://user-images.githubusercontent.com/60636357/99760404-83db6d00-2aa8-11eb-9dd7-0330464ca13a.png)

Code:
api_config = {method:'POST', header:{'Accept': 'application/json','Content-Type':'application/json'}, body:{'name': 'test19','salary': 'test4','age': '31'}};
api http://dummy.restapiexample.com/api/v1/create
js obj = JSON.parse(api_result)
echo `api_result`
js VarId= obj.data.id
echo `VarId`

api_config = {method:'GET', header:{'Accept': 'application/json','Content-Type':'application/json'}};
api http://dummy.restapiexample.com/api/v1/employee/`VarId`
js obj = JSON.parse(api_result)
echo `api_result`
js MsgFetch= obj.message
echo `MsgFetch`

Error:
ERROR - jSON Parse error: Unrecognized token '<'

**Comment by kensoh** [comment] 2020-11-25 03:19
Hi @joginderrohilla sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I can replicate the issue, it seems to be a problem with this API web service. Consider the following code -

```
api_config = {method:'POST', header:{'Accept': 'application/json','Content-Type':'application/json'}, body:{'name': 'test19','salary': 'test4','age': '31'}};
api http://dummy.restapiexample.com/api/v1/create
echo `api_result`
js obj = JSON.parse(api_result)
```

Instead of returning a text response of a JSON structure, the following HTML text is returned with error 'Too Many Requests'. This suggests that the web service owner has not provided enough limits for the service to be freely available to all its potential users. Thus, intermittently when there are many users accessing and exceeding the daily / monthly limit, error happens. Since the response is HTML, trying to do `JSON.parse()` will throw the expected error.

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Too Many Requests</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .code {
                border-right: 2px solid;
                font-size: 26px;
                padding: 0 15px 0 15px;
                text-align: center;
            }

            .message {
                font-size: 18px;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="code">
                429            </div>

            <div class="message" style="padding: 10px;">
                Too Many Requests            </div>
        </div>
    </body>
</html>
```

Closing the issue for now but please lemme know if you have any input or question.

**Closed by kensoh** 2020-11-25 03:19 UTC

**Comment by kensoh** [comment] 2020-11-26 06:22
Adding on, by doing the `echo` step before the JSON.parse() function, you will be able to see the cause of error above, which is the webservice hitting limit and not willing to respond to the API call.

**Comment by kensoh** [comment] 2020-11-26 06:23
Doing `echo` after the error will not be able show the response and cause of error, because program quits by then.

**Comment by joginderrohilla** [comment] 2020-11-26 06:27
Thanks Ken, I found the limit error.
