### ISSUE TITLE
Preserving URL state between iterations (optional to specify continuation URL) - done

### ISSUE THREAD

**Issue by blinkh00** [kelaberetiv/TagUI#1087] opened 2021-07-27 12:09 UTC
Hi !

Refer flow, data and output as attached, each record update, browser will show about:blank webpage. Kindly advice, how skip/remove the webpage (about:blank). Thank you.

**data.csv**
========
# | PFR | Item | Qty
-- | -- | -- | --
1 | BL/0000002 | 642-0177-85 | 500
2 | BL/0000002 | 642-0177-85 | 600

**test.tag**
=======
if iteration==1
	http://uwcerpapp/WSWebClient/Default.aspx
	keyboard [tab]
	wait 0.1
	type User Name as [clear]`usrid`
	type Password as [clear]`pwd`
	type Configuration as [clear]`cname`
	click Sign In
	wait 5
	keyboard [ctrl][o]
	wait 3
	keyboard Customer Order Blanket Lines
	wait 2
	keyboard [enter]
	wait 0.5
	keyboard [f4]
	wait 10

click new.png
wait 0.5
type Order as `PFR`
keyboard [tab]
wait 0.5
keyboard [tab]
wait 0.5
type Item as `Item`
keyboard [tab]
wait 1
click OK1.png
wait 1
keyboard [tab]
wait 0.5
keyboard [tab]
wait 0.5
type Blanket Quantity as `Qty`
keyboard [tab]
wait 0.5
keyboard [ctrl][s]
wait 0.5
[about_blank.pdf](https://github.com/kelaberetiv/TagUI/files/6885209/about_blank.pdf)

**Comment by ruthtxh** [comment] 2021-07-28 04:26
Hi @blinkh00 to prevent TagUI from opening a new browser in between datatable iterations, you may run the flow with speed option like this:

```
tagui test.tag data.csv -speed
```

**Comment by kensoh** [comment] 2021-07-28 05:21
Adding on, I can replicate this. The usual setup for this situation is below.

I think there is some design constraint that need to go to about:blank let me check again.

```
if iteration equals to 1
    initial_url_for_login_etc
    // login steps

url_for_rest_of_iterations
// main steps to repeat
```

**Comment by kensoh** [comment] 2021-07-28 05:32
The change was to address situations when a URL is not given and fail error checking --> https://github.com/kelaberetiv/TagUI/issues/97

Looking further..

**Comment by kensoh** [comment] 2021-07-28 05:45
I've checked and confirm that this is by design. Because the underlying engine used for automation is CasperJS, it requires visiting a webpage when a URL is not provided. But for subsequent iterations, visiting back the original URL doesn't make sense. So the workflow is required to provide 1 URL for first iteration (to do login etc), and 1 URL for main repetition 

```
if iteration equals to 1
    initial_url_for_login_etc
    // login steps

url_for_rest_of_iterations
// main steps to repeat
```

In this case, you can provide the URL to start for subsequent iterations by providing it before this line -

```
click new.png
```

**Comment by kensoh** [comment] 2021-07-28 05:47
Alternatively, instead of using datatable, you can consider processing the csv file directly this way --> https://github.com/kelaberetiv/TagUI/issues/1083

**Comment by kensoh** [comment] 2021-07-28 06:34
Hi @blinkh00, thanks for raising this! I found a technical workaround and has implemented an update. With this update, TagUI will preserve the URL state between iterations so that it will continue from the last URL where it left off, if no URL is provided in the main body of where to visit, but only provided during iteration 1. With this change both your workflow will work, and also existing user workflows which specifies a specific continuation URL will continue to work.

**continue where webpage left off**
```
if iteration equals to 1
    initial_url_for_login_etc
    // login steps

// main steps to repeat
```

**specify a specific url for iteration**
```
if iteration equals to 1
    initial_url_for_login_etc
    // login steps

url_for_rest_of_iterations
// main steps to repeat
```
If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

Alternatively, you can manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing TagUI installation. After unzipping, drag all the folders and files under TagUI-master\src to your existing tagui\src folder. This will apply this update to your TagUI.

**Comment by kensoh** [comment] 2021-08-06 02:28
Above commit added fix to the issue cause by this change to live mode URL step.

**Comment by kensoh** [comment] 2021-08-06 02:29
Thanks to @lookang for your feedback!

**Comment by kensoh** [comment] 2022-07-15 07:48
Closing since this change has made its way into the latest packaged release.

**Closed by kensoh** 2022-07-15 07:48 UTC
Labels: feature
