### ISSUE TITLE
Keyboard command not working on some machines - pending logs

### ISSUE THREAD

**Issue by Shubhavatar** [kelaberetiv/TagUI#1197] opened 2022-03-09 09:40 UTC
The tagui scripts work fine on my machine and a few other machines of my peers, but the keyboard commands do not work on my user's machine.
They also have the same version of tagui installed as me.
I've tried reinstalling OpenJDK (the amazon corretto - and also tried repairing the installation on their machine after reading thread #1143  ).
I also checked if the antivirus is causing any blocks on their machine, but that does not seem to be the case.
They are using a 64-bit Windows system (in reference to issue #1127  ).
The SikuliX window that opens during execution is generally blank.
The behavior is: All commands work properly until it reaches a keyboard command in the script, after that, it prints that keyboard command in the log (command prompt that started the tagui script execution) and then stops continuing. It does not proceed with execution nor terminates. The SikuliX window is generally blank on their machine. 
Does that mean that visual automation/keyboard was not installed properly? - if yes, how do I fix that?

The user is in a highly isolated environment with VPNs and other restrictions.

**Comment by ruthtxh** [comment] 2022-03-11 07:41
Hi @Shubhavatar after running the automation can you collect the log file in tagui\src\tagui.sikuli folder and attach them here so we can have more clues. Thanks!

**Comment by Shubhavatar** [comment] 2022-03-11 07:46
Hi @ruthtxh  thank you for the response! I had checked that log file, it is empty.

**Comment by ruthtxh** [comment] 2022-03-14 01:50
Hi @Shubhavatar, I see.

Some things you can try are:
1. To reinstall TagUI as well
2. Check if there is another instance of java installed apart from the OpenJDK you installed

**Comment by Shubhavatar** [comment] 2022-03-14 06:48
I am unable to connect to update it locally on their machine thanks to VPN, but I was able to copy/paste my local tagui installation in their machine, to no avail though.

Java -version returns this on my machine:
![image](https://user-images.githubusercontent.com/72294637/158119250-16727bb8-1573-43e8-a7ee-a2a6d8fe1ec3.png)

The user's machine has a higher version, but a similar output.

What else could we check?

**Comment by ruthtxh** [comment] 2022-03-14 14:21
Hi @Shubhavatar I see. Can you copy and paste over a fresh copy of TagUI from [here](https://github.com/kelaberetiv/TagUI/archive/master.zip) instead of your local copy?

There is a jython file that SikuliX uses to set up on the first visual automation run, after which it is shifted away and if you have ran TagUI on your machine before, your copy may not contain all the files needed for the setup on a new machine.

**Comment by Shubhavatar** [comment] 2022-03-16 08:12
I see, will try this once, thank you!

**Comment by Shubhavatar** [comment] 2022-03-16 18:09
Hi @ruthtxh I tried your approach, but the command shell froze at the keyboard command even after fresh copy/paste of the folder.

**Comment by ruthtxh** [comment] 2022-03-17 01:40
Hi @Shubhavatar I see, in that case the issue is most likely the java installed on that machine.

Perhaps you can check if there are any other instances of java installed that might be interfering. 

Or try rolling back on the OpenJDK version to the one recommended on the TagUI installation page [here](https://tagui.readthedocs.io/en/latest/setup.html) (step 3)

**Comment by imkrishnendu92** [comment] 2022-03-22 04:54
[tagui.log](https://github.com/kelaberetiv/TagUI/files/8321225/tagui.log)
[tagui_windows.log](https://github.com/kelaberetiv/TagUI/files/8321226/tagui_windows.log)


I have same issue so I attached here log file please help me

@ruthtxh

**Comment by ruthtxh** [comment] 2022-03-22 06:25
Hi @imkrishnendu92 
What behavior are you getting? Your logs look fine and the keyboard steps should be executed.

**Comment by imkrishnendu92** [comment] 2022-03-22 08:07
> Hi @imkrishnendu92 What behavior are you getting? Your logs look fine and the keyboard steps should be executed.

lp = 10
pth = "//div[@id='actionBar']//input[@value='PRINT']"
tagui ..\\airlines_loop.tag
//click on print BP button
click //div[@id='actionBar']//input[@value='PRINT']

wait 7
keyboard [space]
wait 3
keyboard C:\\Airlegit\\BoardingPass\\`pnr`.pdf[enter]
wait 5
snap page to `pnr`.png
wait 25

When I ran this script after clicking "Print" button after this step I need to enter "Space button in my keyboard" so it goes to OS level window where I have to put file name and save PDF file but after print button click it won't take "space button in my keyboard" so when I manually press space button next came OS level window where I have to put file name, In File name textbox area first take keyboard [space] then put keyboard C:\\Airlegit\\BoardingPass\\`pnr`.pdf[enter] this path.

**Comment by ruthtxh** [comment] 2022-03-22 09:58
Hi @imkrishnendu92

Currently as per the logs your keyboard step is executing, but not executing in the browser as it is not in focus. To use keyboard step on your browser you need to do a visual automation click first to set the browser in focus. 

Perhaps you can take a screenshot of the print button and save it to the same folder as the flow, then do:
```
click print_button.png
```
After that you can do keyboard step on the browser.

**Comment by kensoh** [comment] 2022-05-09 00:22
Closing since no further inputs for a while. But @ruthtxh do count issues I close as yours if that is required for internal reporting.

**Closed by kensoh** 2022-05-09 00:22 UTC
Labels: query
