### ISSUE TITLE
How to use datatable in module and not restart browser between iterations?

### ISSUE THREAD

**Issue by gem3** [kelaberetiv/TagUI#354] opened 2019-03-13 02:12 UTC
Hello,

I'm trying to make an automation flow.

Ex.

Main flow(as main_flow):
1. Step login
2. loop with datatable(Sub flow as sub_flow)
3. Step logout

In this main_flow file, I put code below.

tagui sub_flow data.csv

But I got error.

ERROR - file not found for step tagui sub_flow data.csv
ERROR - automation aborted due to above

How can I use datatable in module(tagui step)?

Are there some options to use datatable function ?

**Comment by kensoh** [comment] 2019-03-13 13:16
Hi Gem, the `tagui` step only accepts the name of the script to be used but not parameters such as datatable filename.

What you want to achieve is doable, all you have to do is specify the datatable name when running your main script. eg `tagui main_flow data.csv`. After that you can call `tagui sub_flow` in your main script and use the datatable fields as usual with backticks \`field_name\`.

**Comment by gem3** [comment] 2019-03-13 22:15
Hello, kensho.

Thank you for your reply.

It works fine.

TagUI is a really excellent tool!

**Comment by gem3** [comment] 2019-03-14 01:33
Hello,

I can find first record of datatable with`[iteration]` equals to 1.

Are there easy way to find last record of datatable?

**Comment by gem3** [comment] 2019-03-14 06:00
Hello,

To get record number (as recode_num) of datatable,
I try to run codes below.

'load '+p1+' to data_table'
recode_num = data_table.split("\n").length - 1

But I can not load a csv file with p1 option.
I tried

load p1 to data_table
load `[recode_num]` to data_table

What is correct way to use p1 ?

Thank you in advance.

**Comment by gem3** [comment] 2019-03-14 07:15
hello,

load `p1` to data_table

It's works.

**Comment by gem3** [comment] 2019-03-14 08:20
Hello,

I made some code with datatable.
I don't fully understand TagUI function.
(I can not find global variable to use record number.
so I use temporary file to store the record number)

Some improvemet needed!

`if `[iteration]` equals to 1
{
fs = require('fs');
target_file = flow_path+'/'+'record_num.txt';
		if (fs.exists(target_file))
		{
			fs.remove(target_file);
		}

load `p1` to data_table
record_num_save = data_table.split("\n").length - 1

write record_num_save to record_num.txt

//
//Here Login flow
//

}


// Start Sub flow with datatable
load record_num.txt to record_num_save
record_num = record_num_save[0].split('\n')
tagui flow_sub.txt
// End Sub flow with datatable


if `[iteration]` equals to record_num
{

//
//Here Logout flow
//

}
`

**Comment by gem3** [comment] 2019-03-14 08:56
Hello,

I put some login and logout steps.
It works but not what I expected first.

With datatable, it loops after browser close.

Are there some ways to loop with browser keep alive?

**Comment by kensoh** [comment] 2019-03-14 13:56
You can try running TagUI with speed option. By default TagUI will restart browser between datatable iterations and pause 3 seconds between iterations to ensure execution robustness from computer memory issues for large datatables taking 10 or more hours to run.

With speed option it does not restart browser. You can use the if condition to check the iteration number to perform login and logout according.

```
if `[iteration]` equals to 1
tagui login_flow

your main logic for automating with the datatable parameters

if `[iteration]` equals to total_records
tagui logout_flow
```

**Comment by gem3** [comment] 2019-03-15 06:44
Hello,
It works well.
Now., I can step ahead.

TagUI is really useful and easy to use.

Thank you for your effort to develop.

**Comment by joginderrohilla** [comment] 2020-03-30 10:47
Hi Ken,

I am using datatable in flow file execution and using below command having speed parameter, still its making my browser  URL to "about:blank" for second iteration where i am skipping the launch and login code.

It is suppose to skip browser restarting but it's not working.

C:\Users\jrohilla>tagui "E:\TagUI\Flow_Apptivo_Invoice\Flow_Create_Invoice.tag" -chrome trade_data.csv -speed

Am I missing anything, please suggest.

**Comment by kensoh** [comment] 2020-03-31 02:04
Hi @joginderrohilla can you paste your code and the log file now?

The expected behaviour will be browser does not restart, but TagUI will still run the entire block of code in your workflow in the 2nd iteration, unless there is special handling.

For example, below workflow -

```
https://google.com
type q as `query`
wait 3
```

With below csv -
```
#,query
1,a
2,b
3,c
```

When run with `tagui workflow.tag data.csv -speed` it will do the queries 3 times without restarting the browser. However, if your code looks like below, during 2nd iteration, because TagUI is not instructed to go to the webpage, it will not go there from the blank page on launch.

```
if `[iteration]` equals to 1
    https://google.com

type q as `query`
wait 3
```

The trick for handling login is do the login for the first iteration, and after the if statement, add a URL which is pointing to the logged-in state for the website. This way, do not need to login multiple times, website will treat it as the same session.

**Comment by joginderrohilla** [comment] 2020-03-31 02:32
Hi Ken,
Yes, I have not added the logged - in -state URL/home page URL after if statement. Ill do that.

Now my query is, Will it keep my session on, even if i have thousand iteration to do. Can we assume each website is designed /developed in such way that after first iteration we can directly launch home page and start working from there?

**Comment by kensoh** [comment] 2020-03-31 02:53
It will keep the session on, however each website has different timeout limits. Some website will auto-logout a user after 1 hour for example. For this, you'll need to test what is the logout period for the website, so you can do another login before that happens.

It depends on your website, but so far from my experience the browser login state should be retained in between iterations when you use the -speed option, as the web-browser does not restart. For some less sensitive website, even after restart the login state is still there. For more secured websites each closing of browser will rest the login state and user have to login again.

**Comment by joginderrohilla** [comment] 2020-03-31 03:04
Thanks Ken, make sense

**Closed** 2020-03-31 06:35 UTC
Labels: general

**Comment by joginderrohilla** [comment] 2020-03-31 17:00
Hi Ken, I am using below code to get record count, but its not working for me:

**Execution command:**
C:\Users\jrohilla>tagui "E:\TagUI\Flow_Apptivo_Invoice\Flow_Create_Invoice.tag" -chrome trade_data.csv -speed

**flow file code**
echo `p1`
load `p1` to data_table
record_num = data_table.split("\n").length - 1
echo `record_num`

**Output for Above Code:**
trade_data.csv
load trade_data.csv to data_table
ERROR - cannot find file trade_data.csv

trade_data.csv is placed at path C:\Users\jrohilla

**Comment by kensoh** [comment] 2020-03-31 17:22
Data table is not used this way. Whenever you have a .csv file as parameter, TagUI will treat that file as the data table and loop through to execute multiple iterations. See tagui\flows\samples\6_datatables.tag for example. Due to this design, I don't think a .csv file can be passed in as input correctly to be used.

**Comment by kensoh** [comment] 2020-03-31 17:25
To get the iteration number when using datatable, use this TagUI variable -

```
echo `[iteration]`
```

**Comment by joginderrohilla** [comment] 2020-04-01 01:50
Yes Ken i understand that, flow file takes it as datatable if there is csv in parameters.

I was trying to get total rows in datatable, can you please help me with that.
As per above code by gem3 its not working.

**Comment by kensoh** [comment] 2020-04-01 03:46
I'm not sure what went wrong on your laptop, maybe for some reason the trade_data.csv is not on the computer in the same folder. Try running TagUI from the E:\TagUI\Flow_Apptivo_Invoice folder with the trade_data.csv there. To see if it helps.

On my Mac, I can run and show output correct whether I run from the flow folder or from another folder. The following flow file and csv and output works for me -

```
echo `p1`
load `p1` to data_table
record_num = data_table.split("\n").length - 1
echo `record_num`
echo `[iteration]`
```
```
#,query
1,a
2,b
3,c
```
```
START - automation started - Wed Apr 01 2020 11:44:04 GMT+0800 (+08)

a.csv
load a.csv to data_table
3
1

FINISH - automation finished - 0.2s
```

**Comment by joginderrohilla** [comment] 2020-04-02 16:26
Hi Ken, 

I am running flow with keep data file on same path, not sure why it is searching the tarde_data.csv file at path-C:\Users\jrohilla

please find below error:

C:\Users\jrohilla>tagui "E:\TagUI\Flow_Apptivo_Invoice\Flow_Create_Invoice.tag" -chrome trade_data.csv -speed
ERROR - cannot find C:\Users\jrohilla\trade_data.csv

**Comment by kensoh** [comment] 2020-04-02 17:10
Try this -

```
cd E:\TagUI\Flow_Apptivo_Invoice
tagui Flow_Create_Invoice.tag trade_data.csv -speed
```

or this -

```
tagui E:\TagUI\Flow_Apptivo_Invoice\Flow_Create_Invoice.tag E:\TagUI\Flow_Apptivo_Invoice\trade_data.csv -speed
```

**Comment by joginderrohilla** [comment] 2020-04-03 04:30
Hi Ken,
Below worked for me, Thanks
tagui E:\TagUI\Flow_Apptivo_Invoice\Flow_Create_Invoice.tag E:\TagUI\Flow_Apptivo_Invoice\trade_data.csv -speed

Queries:
1) Why was it not working when we call flow file in double quotes, and it was not able to find data file
2) why do we not require backticks  for recod_num in below code, since its a variable.
if `[iteration]` equals to record_num

**Comment by kensoh** [comment] 2020-04-04 09:43
Hi @joginderrohilla, great!

1. Yes this can be confusing. Backticks are used when text is expected in normal TagUI steps. For conditions, variables do not need backtick. For example, below code. However here \`[iteration]\` is actually to reference the data table value, so it follows the syntax to reference data table values - https://github.com/kelaberetiv/TagUI/tree/pre_v6#datatables

```
a = '1'
if a equals to '1'
    echo YES
else
    echo NO
```

2. Because in your code, you only count and read value to record_number for 1st iteration -

```
if [iteration]==1
{
//Launch Apptivo application**********
tagui Flow_Apptivo_Login.tag
//Get Total Entries and Navigate to Invoice Page
load p1 to data_table
record_num = data_table.split("\n").length - 1
echo Total no. of records to be processed: record_num
click link_financials
click link_invoices
//Verify Invoice Page Loaded**************
wait 3
check present('//h1/a/span[text()="Invoice"]') | Invoice Page loaded | Invoice Page havent loaded
}
```

3. When -speed option is used, Chrome will not restart at the end of each iteration, so with that design it does not close at the end of the automation. You can try using visual automation to close the Chrome window if it is the last iteration, to see if that works for your use case.

**Comment by joginderrohilla** [comment] 2020-04-04 13:23
Thanks Ken, That make sense now
