### ISSUE TITLE
ERROR - can't find module webpage - pending checks and replication details

### ISSUE THREAD

**Issue by FooZhiRuiHSC** [kelaberetiv/TagUI#1163] opened 2022-01-13 09:29 UTC
Hi, I recently reset my desktop and re-installed tagui and python. Was running my RPAs and encountered "ERROR - can't find module webpage" on several of my scripts.

Attached is a sample of 2 scripts. "Globe3Boot.tag" currently works for my desktop, while "SingtelWebsiteScrapper.tag" does not work and immediately gives the above error.

How should I go about troubleshooting this?

[taguiScripts.zip](https://github.com/kelaberetiv/TagUI/files/7861552/taguiScripts.zip)

**Comment by kensoh** [comment] 2022-01-14 04:21
Hi @FooZhiRuiHSC, it seems that SingtelWebsiteScrapper.tag wasn't meant to be run on its own, the first line is already referring to a variable website. Maybe there are other dependency like tagui_local.csv not included.

I haven't come across this error message before, some ideas to try -

1. delete TagUI by removing the tagui folder
2. uninstall RPA for Python and delete its tagui or .tagui folder under r.tagui_location() folder
3. install TagUI and RPA for Python again
4. run `tagui update` to make sure you have the latest version

The error message isn't from TagUI codebase, probably in one of the components used by TagUI.

**Comment by FooZhiRuiHSC** [comment] 2022-01-14 06:11
Hi,

I am not able to share the tagui_local.csv file with you, as it contains confidential records. However, I can confirm that the file exists and is in the same folder as the .tag script.

I uninstalled tagui as you suggested. Was not aware that there is a RPA for Python package. I reinstalled tagui and installed RPA for Python via pip install rpa. When running the .tag script, the "ERROR - can't find module webpage" still appeared.

I found my old tagui installer (version 6.14) and reintalled tagui again with this version. This time the SingtelWebsiteScrapper.tag script runs. Was there a change in syntax after 6.14, or some other notable tweak that might have broken my old script?

**Comment by kensoh** [comment] 2022-01-14 07:57
I see.. Between v6.14 and v6.105 there are a lot of changes and many bug fixes. It might be a change that fixes a bug on incorrect syntax. But it is hard to know the root cause because I cannot replicate the error on my side. I can only say that this error message is not part of TagUI source code, so it must be a component.

But I cannot find the word webpage in your script, so I'm not sure where troubleshooting can be done. You can try joining the weekly Zoom Q&A call next week to see if any more clues can be found - https://github.com/kelaberetiv/TagUI/issues/914

**Comment by FooZhiRuiHSC** [comment] 2022-01-19 09:03
Interestingly, when I replace all the variables with static values, the "ERROR - can't find module webpage" still occurs. This is even the case when I use https://google.com like you did.

What I did observe is that when I start the script from cmd, Chrome opens and remains in the about:blank page. The website never loads and after a few seconds Chrome closes and cmd returns the ERROR - can't find module webpage

If your hypothesis is correct and a component is missing, what exactly is this component? I've uninstalled tagui and tried both installation methods on the tagui installation guide (using the executable, and using the zip file). I've also installed OpenJDK, Chrome, and added tagui/src to path.

I'll jump on to the zoom call to discuss further.

**Comment by kensoh** [comment] 2022-01-20 03:24
Sure, this is a very interesting error! Today I'll be at a TagUI study session by Anders, a RPA influencer.

But my team-mate Ruth will be on the call. For next week both of us will be on the Zoom call.

From above data points, it is almost as if some component is missing from Chrome itself, and the error is somehow returned from Chrome. Because TagUI hasn't yet done anything on Chrome to automate anything. Let's find out.

**Comment by kensoh** [comment] 2022-01-30 00:25
Closing this - issue found to be the use of `Object` as the header in tagui_local.csv. This is a reserved keyword for JavaScript. Not adding to documentation for now because this is rare and tends to confuse users than help. Fyi @ruthtxh

**Closed by kensoh** 2022-01-30 00:25 UTC
Labels: query
