### ISSUE TITLE
can't get Chrome visible mode to work - gathering replication steps

### ISSUE THREAD

**Issue by SetSails** [kelaberetiv/TagUI#511] opened 2019-07-18 21:32 UTC
Hi kensoh,

I'm trying to run the sample `./tagui samples/1_yahoo chrome` in visible Chrome mode - i'm running mac os/x 10.13.6 (17G65)

It does open a new Chrome window (which by the way has none of my google accounts active) but then just doesn't do anything.

What am I missing ?

Without appending `chrome` to the command it does complete successfully in the background.

Thank you & Best Regards
Fabian

**Comment by kensoh** [comment] 2019-07-19 03:25
Hi Fabian, this is interesting issue, have not come across this. (for none of Google accounts active, that is by design. so that the TagUI has its own Google Chrome session without disrupting or restarting existing open Chrome browser by user).

1. Can I check if you have downloaded a packaged installation for macOS from here -
https://github.com/kelaberetiv/TagUI#packaged-installation

2. After Chrome window launches and hangs there, can you paste the contents of the file tagui/src/tagui_chrome.log into this GitHub issue? I'm trying to see if TagUI is able to connect to Chrome and if there is response back from Chrome.

During the first run, just like a new Chrome installation, the Chrome browser will prompt you for some initial setup, you can choose your options and Chrome won't ask again the next time.

**Comment by ck81** [comment] 2019-07-19 07:03
@SetSails  says:
> It does open a new Chrome window (which by the way has none of my google accounts active) but then just doesn't do anything.

For TagUI, it's difficult to debug when there are too many commands.  To find out where might be the problem, I like to try this two-liner to see if TagUI works on your machine or not:

~~~javascript
https://google.com
LIVE
~~~

Save the above in a file, say test.txt. Then run the script using:
~~~
tagui test.txt chrome
~~~

If you see the chrome browser being launched and the google web page displayed, then you will know that TagUI is running properly on your machine.  Note: the "LIVE" command is to put TagUI in interactive mode.  Without this, the browser might launch, display the google page and then immediately close in the blink of an eye, and you might thought it's not working.

By the way, if you see the following error message
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

you might need to install the OpenSSL library on your Mac.

Please refer to the article for details: "dyld: Library not loaded error on macOS (OpenSSL missing)" #86

**Comment by kensoh** [comment] 2019-07-19 08:35
Thanks CK for adding on to share your tips on finding out root cause of the issue!

**Comment by kensoh** [comment] 2019-07-24 10:09
Closing for now until further inputs

**Closed by kensoh** 2019-07-24 10:09 UTC
Labels: query
