### ISSUE TITLE
How to run TagUI on Chromium browser? (for eg on 32-bit Ubuntu)

### ISSUE THREAD

**Issue by RichardNeill** [kelaberetiv/TagUI#336] opened 2019-01-29 23:28 UTC
1. Ubuntu ships with "Chromium", not Google-Chrome.
The workaround is to symlink: 
 /usr/bin/google-chrome -> /usr/bin/chromium-browser
but ideally, TagUI should try both.

2. Even though phantomjs IS installed (in /usr/bin/phantomjs), TagUI can't find it.
Again, a symlink fixes it:
  /usr/local/bin/phantomjs -> /usr/bin/phantomjs
but TagUI should look in $PATH rather than hardcoding /usr/local/

**Comment by kensoh** [comment] 2019-01-30 00:18
Hi Richard, thanks for raising this and taking the time to share! Adding on, 

1. TagUI will show a message to user if Chrome cannot be found and ask user to update src/tagui chrome_command setting to point to the right command in user's environment. This setting has to be decided by user because TagUI should not make the decision on user's behalf whether to use Chrome or Chromium for automation.

2. If the packaged installation zip is used, which is the recommended way to setup TagUI, there will be a PhantomJS within src folder and there shouldn't be a need to do further configuration. TagUI will use PhantomJS from directory, NodeJS installation over the one installed locally by user.

**Comment by RichardNeill** [comment] 2019-01-30 00:45
Thanks very much, I see your point on 1, but for Linux, the open-source Chromium IS the browser that people call Chrome. So you maybe could fall back to Chromium if google-chrome isn't installed.

Re 2, I think I made an obvious mistake. I clicked the first "master.zip" link in the install instructions, which is at: "Tip - to try cutting edge version with the latest features, download master.zip"
Indeed, the  Linux "unzip and run" link does have phantom included, and that works. Thank you.

**Comment by kensoh** [comment] 2019-01-30 00:59
May I check with you your thoughts on the following - Do you know if most people using Ubuntu installs Chrome or uses the default Chromium? How is your experience so far using TagUI with Chromium?

I'm hesitant to officially support Chromium as TagUI was developed and tested with Google Chrome but hasn't been tested at all with Chromium, so it might introduce unexpected behaviour when users use it with Chromium.

**Comment by RichardNeill** [comment] 2019-01-30 01:09
So far, Chromium is working fine for me. On Ubuntu, in general, nobody I know ever installs the "Google" build, because it's closed-source and unsupported, whereas Chromium is packaged by upstream as the distro default. So "Chrome" just means Chromium.

**Comment by kensoh** [comment] 2019-01-30 15:53
@Aussiroth I know what @RichardNeill means now, Chrome is no longer supported for 32-bit versions of Ubuntu. But for 64-bit versions it still runs. I'm leaning towards not auto-detecting and deciding for users whether to use Chrome or Chromium as 64-bit Ubuntu still runs Chrome, and there is graceful error message asking user to update their chrome_command setting.

I think there are still some key RPA features yet to be done (enterprise features such as orchestration through local agents, reporting of automation executions etc), probably not a good idea to go into customizations for now. Because there will be a lot more customizations to cater for.

**Comment by Aussiroth** [comment] 2019-01-31 04:18
I see, if there is mixed use of Chrome/Chromium across linux platforms it might be better to leave it as is, but clarify in the error message that users can update to use Chromium installation if it is what they have installed.

**Comment by kensoh** [comment] 2019-02-10 06:22
Closing the issue for now, updated issue title, and added following example to symlink on Ubuntu 32-bit versions which can't run Google Chrome. Ubuntu 32-bit users can either use below symlink to use TagUI with Chromium, or update src/tagui file chrome_command to point to their Chromium path.

```
ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
```

**Closed by kensoh** 2019-02-10 06:22 UTC
Labels: query
