### ISSUE TITLE
PhantomJS version outdated - use updated copy from website for OpenSSL v1.1

### ISSUE THREAD

**Issue by gauravkeerthi** [kelaberetiv/TagUI#932] opened 2021-02-07 12:18 UTC
suggest that the code library for phantomjs is updated to the newest version from https://phantomjs.org/
I've tried the code with the new version and it works.

**Comment by kensoh** [comment] 2021-02-07 18:25
Hi Gaurav, thanks for raising this! Can you tell me more what you mean by the code library and how to replicate any error?

I've checked the PhantomJS URL above, the downloaded version is v2.1.1, and that's the version packaged with TagUI.

Here's a video with more contextual details of above findings - https://www.youtube.com/watch?v=I4HoSzD38FU

**Comment by gauravkeerthi** [comment] 2021-02-08 08:11
ref to this: https://github.com/kelaberetiv/TagUI/issues/86#issuecomment-689781003

**Comment by gauravkeerthi** [comment] 2021-02-08 08:12
anyway when i downloaded the code it threw up an error. i updated the phantomjs and it works. not sure what the reason was. 
and I'm still using libressl 2.8.3

**Comment by kensoh** [comment] 2021-02-08 08:37
Thanks Gaurav for raising this!

It looks like though both copies have same version, the file size differs. We'll keep the issue open to investigate further onto whether to change the package or the solution at #86 or work out another implementation that can be more seamless.

**downloaded copy**
![download](https://user-images.githubusercontent.com/10379601/107194811-86a48900-6a2b-11eb-9337-e5b919669f74.png)

**packaged copy**
![mac_package](https://user-images.githubusercontent.com/10379601/107194828-899f7980-6a2b-11eb-8561-87047243583a.png)

**Comment by kensoh** [comment] 2021-02-26 17:08
Adding on another datapoint from my colleague that above is true for him as well on Big Sur release.

This PhantomJS version from the website will have to be included into TagUI in the next release.

**Comment by kensoh** [comment] 2021-03-05 07:30
Another datapoint from another colleague that version from website works for OpenSSL v1.1.

This is confirmed, to use that PhantomJS v2.1.1 instead of the existing packaged PJS v2.1.1.

**Comment by kensoh** [comment] 2021-03-05 07:36
Re-assigning as a bug introduced with newer versions of Mac OS. To be fixed in next release. Or users can download directly from below link. After unzipping, put contents of unzipped folder into tagui/src/phantomjs folder.

https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

**Comment by kensoh** [comment] 2021-03-07 17:08
Until next release, have updated installation troubleshooting instructions to use latest PJS from provided zip URL

**Comment by kensoh** [comment] 2021-03-07 17:22
Fyi @ruthtxh

I've updated the Having problems link here to be more visible (some people will miss it when it is the last line)
https://tagui.readthedocs.io/en/latest/setup.html

Have updated troubleshooting steps for macOS to download new PhantomJS zip to replace existing phantomjs
https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-windows

In the next release, will review the various components of TagUI to put in the latest possible (including PJS).

**Comment by kensoh** [comment] 2021-05-20 22:55
Looks like similar issue for Linux? (from https://github.com/kelaberetiv/TagUI/issues/787#issuecomment-844942539) Needs to refresh.

https://phantomjs.org/download.html

![Screenshot 2021-05-21 at 6 54 35 AM](https://user-images.githubusercontent.com/10379601/119058699-6eb4ac00-ba01-11eb-9d1f-0a575980feea.png)

**Comment by kensoh** [comment] 2021-06-18 03:12
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0

**Closed by kensoh** 2021-06-18 03:12 UTC
Labels: bug
