### ISSUE TITLE
click '+image_var+' - using dynamic image identifiers with variables

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#464] opened 2019-06-21 14:48 UTC
The following works:
```javascript
img = "save.png"
if present('save.png')
{
	echo "image found!"
}
click save.png
```

Trying to re-use the codes, I put the image as variable.  The following works:
```javascript
img = "save.png"
if present(img)
{
	echo "image found!"
}
click save.png
```

But the following does not work:
```javascript
img = "save.png"
if present(img)
{
	echo "image found!"
}
click '+img+'
```

This is the Error Message:
> image found!
> click save.png
> ERROR - cannot find save.png

**Comment by kensoh** [comment] 2019-06-22 15:54
Hi CK, this is an interesting use case. I think the problem is because when you use dynamic variables with images, TagUI during the parsing does not yet already foresee that the variable is going to be an image file, as variables can be formed during execution and from different sources, it won't know in advance that it is an image selector.

```
img = 'save.png'
click '+img+'
click `img`
```

Use the following instead to work, to give TagUI the clue that the identifier is going to be an image -
```
img = 'save'
click '+img+'.png
click `img`.png
```

**Comment by kensoh** [comment] 2019-06-22 15:55
Fyi \`variable\` is the newer way of referencing variables. the previous way '+variable+' still works.

**Comment by ck81** [comment] 2019-06-24 07:23
> Use the following instead to work, to give TagUI the clue that the identifier is going to be an image -
> 
> ```
> img = 'save'
> click '+img+'.png
> click `img`.png
> ```

Yes, this worked! Thanks!

**Comment by kensoh** [comment] 2019-06-24 14:30
Cool! I'll close this issue for now 👍

**Closed by kensoh** 2019-06-24 14:30 UTC
Labels: query
