### ISSUE TITLE
Excel 内中文读取问题 - change pc language settings to enable UTF-8

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1231] opened 2022-05-14 02:33 UTC
@ruthtxh @kensoh    当Excel内包含中文，读取的时候会有问题。
excel内容：
![image](https://user-images.githubusercontent.com/76672577/168407560-35121224-419b-402e-8ef1-4382951620d7.png)

代码：
```
// 把cmd设置成UTF-8
run cmd /c chcp 65001

//读excel
data_array = [1.xlsx]sheet1!A1:B3
echo `data_array`
```

结果：
![image](https://user-images.githubusercontent.com/76672577/168407613-257194c1-71b1-471f-a068-32f60b3914bc.png)

我尝试直接把变量写入txt，发现txt内也是乱码。

请问如何解决呢？ 

另外经常看到这句， A duplicate file name exists, or the file   cannot be found.  请问是什么原因？？？

谢谢。

**Comment by kangyiwen** [comment] 2022-05-14 02:38
`dump `data_array` to 0.txt`

结果 0.txt 内是：  `1,k,2,�й�,3,y`

**Comment by kensoh** [comment] 2022-05-14 14:28
Hi @ruthtxh, when I create the Excel feature, I did not test for non-English languages.

You can try debugging to trace, and see where is the weak link, and if there is a way to improve to support international characters.

For Windows, the method used is VBScripting to control and read from Excel. There should be some temporary files in tagui/src folder to see the VBscript code to test with wscript or cscript command.

**Comment by kensoh** [comment] 2022-05-14 14:29
I don't have Excel app now after leaving AI Singapore, and no access to Windows laptop.

**Comment by kangyiwen** [comment] 2022-05-15 02:38
我测试txt文件中文读取写入，是正确的，没有乱码。

```
//读txt
load 0.txt to data
echo `data`

//追加写入txt
write `data` to 0.txt

//读txt
load 0.txt to data
echo `data`

wait 5
```

结果：
![image](https://user-images.githubusercontent.com/76672577/168454761-f4a52a0d-4825-4f24-8ecb-60fa98491d7a.png)

@kensoh @ruthtxh   对中文内容的支持还是非常重要的，Excel word 的处理几乎大部分流程都会用到。 
请在迭代过程中，同时测试WORD，PDF的中文支持，谢谢。

**Comment by kensoh** [comment] 2022-05-16 09:51
The Excel integration involves VBScript (Windows) or AppleScript (Mac) API in order to read and write to Excel app.

Looks like probably the issue is during passing data from Excel to TagUI. @ruthtxh you can check https://github.com/kelaberetiv/TagUI/issues/1231#issuecomment-1126726218

May be do something simple like below and there would be a `excel_steps.vbs` file in tagui/src folder.

You can view/edit it to debug and run with `cscript excel_steps.vbs //NoLogo` command from command prompt.

```
data = [abc.xlsx]Sheet1!A1
echo `data`
```

**Comment by kensoh** [comment] 2022-05-16 09:52
PS - for Word and PDF, I believe they support Chinese characters, because it is done using clipboard copy

**Comment by ruthtxh** [comment] 2022-05-17 00:57
Hi @kangyiwen this issue was raised before, I found out that the error occurs due to PC settings causing certain programs to display texts differently. Please see solution here:

https://github.com/kelaberetiv/TagUI/issues/1199

**Comment by ruthtxh** [comment] 2022-05-17 00:58
Duplicate of https://github.com/kelaberetiv/TagUI/issues/1199

**Comment by kangyiwen** [comment] 2022-05-17 06:05
谢谢，留个中文截图，看着更方便

![image](https://user-images.githubusercontent.com/76672577/168740133-2d54f90c-1ee2-4b8c-b8fc-9ecd3fe14a94.png)

**Comment by kangyiwen** [comment] 2022-05-17 14:06
@ruthtxh @kensoh    这个方法在中文WINDOWS环境，虽然TagUI可以正常读取excel内中文了，但是一些平时正常的显示中文的软件，现在显示乱码，而且多款软件都是这样的情况。

理解你们都是英语环境做的开发，但如果中文环境使用有这样的问题，发展阻力就会很大。希望通过 TagUI 的后续迭代，解决这个问题。

下面是FTP软件的截图：
![image](https://user-images.githubusercontent.com/76672577/168828217-43c8494b-5e95-4e10-88c5-a0df5c620879.png)

**Comment by kensoh** [comment] 2022-05-17 14:37
Oh, this is a big problem for international users because user computers can't use normal apps and TagUI at the same time.

Maybe reopen, to see if @ruthtxh can explore other ways of solving this problem?

@kangyiwen can you share if you know any command line apps which can display Chinese correctly without making this setting that breaks all apps? It will be helpful to Ruth to have an example of how other command line tools handle international languages other than through UTF-8.

**Comment by twinyk** [comment] 2022-05-17 14:43
学习一下欧洲的开源项目，为你东盟的兄弟们想想，Indonesia bahasa, Malaysia english, 简体中文和繁体中文。新加坡不要自己玩。哈哈哈

从 Windows 版邮件发送

发件人: Ken Soh
发送时间: 2022年5月17日 22:38
收件人: kelaberetiv/TagUI
抄送: Subscribed
主题: Re: [kelaberetiv/TagUI] Excel 内中文读取问题 - change pc language settings (Issue #1231)

Oh, this is a big problem for international users because user computers can't use normal apps and TagUI at the same time.
Maybe reopen, to see if @ruthtxh can explore other ways of solving this problem?
@kangyiwen can you share if you know any command line apps which can display Chinese correctly without making this setting that breaks all apps? It will be helpful to Ruth to have an example of how other command line tools handle international languages other than through UTF-8.

**Comment by twinyk** [comment] 2022-05-17 14:44
还有 印度和越南。

从 Windows 版邮件发送

发件人: wu
发送时间: 2022年5月17日 22:43
收件人: kelaberetiv/TagUI; kelaberetiv/TagUI
抄送: Subscribed
主题: 回复: [kelaberetiv/TagUI] Excel 内中文读取问题 - change pc language settings (Issue #1231)

学习一下欧洲的开源项目，为你东盟的兄弟们想想，Indonesia bahasa, Malaysia english, 简体中文和繁体中文。新加坡不要自己玩。哈哈哈

从 Windows 版邮件发送

发件人: Ken Soh
发送时间: 2022年5月17日 22:38
收件人: kelaberetiv/TagUI
抄送: Subscribed
主题: Re: [kelaberetiv/TagUI] Excel 内中文读取问题 - change pc language settings (Issue #1231)

Oh, this is a big problem for international users because user computers can't use normal apps and TagUI at the same time.
Maybe reopen, to see if @ruthtxh can explore other ways of solving this problem?
@kangyiwen can you share if you know any command line apps which can display Chinese correctly without making this setting that breaks all apps? It will be helpful to Ruth to have an example of how other command line tools handle international languages other than through UTF-8.

**Comment by kensoh** [comment] 2022-05-17 15:26
@kangyiwen can you check with @twinyk an example of an open-source command line tool which can support international languages without changing that Windows setting that break your apps? This will be helpful for Ruth to learn how it is done or reach out to find out more. Also Python is a globally massive application.

Also, maybe you can try if Python can process international languages on command prompt correctly wihtout changing that Windows setting.

**Comment by twinyk** [comment] 2022-05-18 00:50
呵呵，哈哈哈。让市场需求来 洒洒水。


发件人: Ken Soh
发送时间: 2022年5月17日 23:29
收件人: kelaberetiv/TagUI
抄送: matthew; Mention
主题: Re: [kelaberetiv/TagUI] Excel 内中文读取问题 - change pc language settings (Issue #1231)

Although @twinyk seems to be talking 风凉话, maybe we can get some meaningful out from him, to see if his words can be trusted.

**Comment by kangyiwen** [comment] 2022-05-18 00:55
我搜索到这些命令行下的js工具，但我英语水平不行，麻烦  @ruthtxh  看看吧，或者直接找几个作者问问。
![image](https://user-images.githubusercontent.com/76672577/168935175-2e571588-499f-48f2-a3da-40157e24a481.png)


我想到另一个思路，目前只是Excel时有乱码，是否先把 xls 文件做个编码处理，然后再读取？
或者在启动excel的时候，增加什么excel的参数解决问题？

**Comment by ruthtxh** [comment] 2022-05-18 03:30
Hi @kangyiwen

The settings does not affect other apps, I downloaded flashfxp (but evaluation version) and set the language to Chinese and characters are looking fine. 
![image](https://user-images.githubusercontent.com/40910744/168950514-9a7f8a7c-8054-434c-bb5a-2068f79c2e89.png)

This is because the excel app is a non unicode app and global handling has to be done on pc level to handle such apps. I believe this is the solution for excel macro scripts that want to output chinese characters as well and from various forums the solution works fine for Chinese people.

I have set my settings to Chinese (Simplified, Singapore) perhaps you can try around with other language settings and see what works best with your other apps.

**Comment by kangyiwen** [comment] 2022-05-18 06:27
@ruthtxh   我安装了最新版的 flashfxp，安装过程中我看到有语言包的安装选项，新版本可以正常显示中文菜单。

![image](https://user-images.githubusercontent.com/76672577/168970917-e728503b-79a8-4697-b4ab-841ef39e36af.png)

**Comment by kensoh** [comment] 2022-05-18 09:35
That's wonderful! Looks like issue solved.

**Closed** 2022-05-19 02:10 UTC
Labels: query

**Comment by kangyiwen** [comment] 2022-05-20 00:22
用 “UTF-8提供全球语言支持” 还是存在一些问题：

- 一些版本比较低的软件，会出现乱码。
- 部分用到 ini 的软件，读取ini里中文会异常。

大部分成熟软件，都没这问题，只是小工具会这样。

**Comment by lookang** [comment] 2022-06-20 14:45
what is the equivalent terminal code for "chcp 65001" ?

i get error on a mac.
lookang@Opens-MacBook-Pro wogaa % run cmd /c chcp 65001
zsh: command not found: run
lookang@Opens-MacBook-Pro wogaa %
