### ISSUE TITLE
How to prevent overwriting of file downloads with same filename - use hack

### ISSUE THREAD

**Issue by LEES0159** [kelaberetiv/TagUI#621] opened 2019-11-10 16:52 UTC
Hi Mr Soh,

Thanks for answering the previous question  #612. Currently at the last step of the automation and would like to find out if we can prevent the overwriting of the downloaded file. E.g. can we modify the settings to download as XXX.csv then XXX(1).csv so on so forth?

Noted from earlier #469 that the location of the downloaded files are the same as where the scripts are stored. Saw relevant threads (e.g. #28, #133, #483 ) but not too sure if the solution is to add a renaming step at the end of each for loop/ round of download. 

_<Not very familiar with PhantomJS but based on link provided, using renaming csv should require me to know the form i.e. XXX.csv at least?>_
E.g.
var fs = require('fs');
fname = "dl_"+n+".csv"
fs.move("XXX.csv", "`fname`")

Thanks much in advance again! :)
[ura_transac_v5.log](https://github.com/kelaberetiv/TagUI/files/3828704/ura_transac_v5.log)

**Comment by kensoh** [comment] 2019-11-11 05:55
Hi @LEES0159 are you using Chrome to run this automation? (tagui script_name chrome)

If it is Chrome I think by default it will not overwrite, you can searching Chrome settings to see if there is a setting to make it not overwrite. Another way is what you typed above using JavaScript code to rename the files. But it is hard if you do not know the filename.

**Comment by kensoh** [comment] 2019-11-11 05:57
If you have to run the automation invisible you can try `tagui script_name headless` and it will also use Chrome to do the automation but the browser will be invisible and you cannot see it.

**Comment by LEES0159** [comment] 2019-11-11 10:11
Hi Ken, 

I am using Chrome to run this to observe the process(i.e.  "./tagui ../ura_transac_dl/ura_transac_v5 chrome" on command prompt in src folder). I observed that as each loop runs, the file downloaded seemed to be replaced each time (due to same name) yet in the Chrome interface i see that they are not overwrited (i.e XX.csv, XX(1).csv ... etc). Not sure if it is intended to prevent multiple downloads.

Hoping its not some silly mistake i made along the way but was hoping to find a workaround. 

Thanks alot! :)

/Users/leesixian/Dropbox/Screenshots/Screenshot 2019-11-11 18.07.45.png

**Comment by LEES0159** [comment] 2019-11-11 10:17
Hi Ken,

I ran the script using Chrome (i.e. ./tagui ../ura_transac_dl/ura_transac_v5 chrome from the src folder) to observe the dl. The dl is normal on the chrome interface (i.e there is XX.csv then XX.csv(1) etc) but noticed in the ura_transac_dl folder where the script is stored that the downloaded file is repeatedly overwrited for each loop.

Hoping its not a silly mistake i made along the way but hoping to clarify on this or move on if it is a restriction imposed on file downloads.

Thanks so much once again! :)

**Comment by kensoh** [comment] 2019-11-11 10:29
Oh yes, it looks like the behaviour now for current release of Chrome when running TagUI is to overwrite the existing file with the same filename. Do you have the following information?

1. filename of the download (is it the same every time)
2. are you using Windows or macOS or Linux
3. what is the full directory where your script is stored

**Comment by LEES0159** [comment] 2019-11-11 12:23
1. The name of the file download changes each time
2. I am using macOS's terminal
3. the full directory where my script is stored in "/Users/[username]/Desktop/tagui/ura_transac_dl", where the downloads are as well. I go to "/Users/[username]/Desktop/tagui/src" to run the command: "./tagui ../ura_transac_dl/ura_transac_v5 chrome".

Is that where the issue lies? Thanks alot again! :)

Thanks alot!

**Comment by kensoh** [comment] 2019-11-11 18:47
I see.. If the filename is always different it will be hard, because you don't know the filename to rename it to some other name. It is still possible, but the solution will be very complicated so I won't be able to help.

It will involve using run step to call your own bash script to do sorting of files in folder by the timestamp, and then renaming that latest file. Will be too complicated to work, so this scenario may not be possible with the tool.

**Comment by kensoh** [comment] 2019-11-12 04:10
Or unless if you are familiar in Python, then you can use the Python integration to do it easily. Python has an os module which makes it easy to work with files. More details on the integration -

https://github.com/kelaberetiv/TagUI#python-integration

**Comment by kensoh** [comment] 2019-11-12 16:42
There is 1 last solution, that is easy and works, but you must hack TagUI source code. By design, the default behaviour for TagUI is to force Chrome to allow download, but that setting will also make Chrome overwrite the existing file if there is a file with the same filename.

To use this hack solution, edit the file src\tagui_parse.php and search for `setDownloadBehavior`. On that line of code, change `behavior: 'allow'` to `behavior: 'default'` and downloads will not be overwritten but follow Chrome's default setting.

The catch of doing this is next time you upgrade TagUI to a new release with new features, you have to do this hack again, because the codebase will not have this hack.

**Comment by LEES0159** [comment] 2019-11-12 17:32
Tried the last hack and it worked perfectly as intended! Noted that now the downloads are stored as per the chrome settings as well ( not the same as where the script is stored). Thanks so much for your patience and for providing so many solutions to try for:) happy to have completed the first rpa attempt with your help using tagui:)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2019-11-13 06:36 UTC
Labels: query

**Comment by fjchavez** [comment] 2021-08-06 05:54
Hi kensoh,

I have tried to make this change behavior: 'allow' to behavior: 'default', however it is not working for me for version 6.68 
Something am I doing wrong or how could it be done so that the files I download are not overwritten.

**Comment by kensoh** [comment] 2021-08-06 18:08
Hi @fjchavez this still works for me -
![Screenshot 2021-08-07 at 2 06 33 AM](https://user-images.githubusercontent.com/10379601/128553501-4ab47626-c6a7-40a7-8802-90ad1009f4b8.png)

Some further ideas to explore -

1. try search and replace twice because there is now 2 occurrence of that part to be changed
2. check Chrome settings --> advance --> download location. with this hack, the file is saved there

**Comment by kensoh** [comment] 2021-08-06 18:09
CC @ruthtxh
