### ISSUE TITLE
Problem in accessing iframe with frame step

### ISSUE THREAD

**Issue by balwant-sd** [kelaberetiv/TagUI#312] opened 2018-11-13 11:05 UTC
i want to access a element which is present in iframe using their XPath.

First I Step in frame using 
`frame portalLaunchPanels`

it works fine, then when i click on element which present inside iframe using
`click //*[@id="_id150:_id186:1:_id190"]`
it gives a error   
```
frame portalLaunchPanels
snap page
click //*[@id="_id150:_id186:1:_id190"]
ERROR - cannot find //*[@id="_id150:_id186:1:_id190"]
```
![screenshot](https://user-images.githubusercontent.com/44574296/48409351-9d32db80-e761-11e8-9441-a189bca70be6.png)

![screenshot from 2018-11-13 16-33-39](https://user-images.githubusercontent.com/44574296/48409517-0adf0780-e762-11e8-967b-8b1bb7d6ac1b.png)

What i do ??

**Comment by Aussiroth** [comment] 2018-11-13 12:56
Hi, you need to put the code to execute in the frame within { and } brackets, similar to if or for steps. Try something like
```
frame portalLaunchPanels
{
snap page
click //*[@id="_id150:_id186:1:_id190"]
}
```

**Comment by balwant-sd** [comment] 2018-11-14 08:04
how can i access below button @Aussiroth 

`
<button class="button ng-binding" ng-click="dialogController.confirmAction()" ng-hide="dialogController.dialogType === TYPE_ALERT" aid="ADM-PartMgmt-UserPopup-ConfirmAction">Apply</button>`

Can i use class name in Xpath ??

**Comment by Fruko** [comment] 2019-01-31 09:17
Hello,

we are using iframes with attribute name that is a hash e.g. (homepages_6766f7f7-25b5-462a-83a6-ef548a303c01). When I try the code mentioned above it does not work. Is there a limitation for using dashes in the attribute name?

![image](https://user-images.githubusercontent.com/10186522/52043975-44453900-2541-11e9-92b5-423921383a87.png)

`frame homepages_6766f7f7-25b5-462a-83a6-ef548a303c01
{
snap page
click //*[@id="start"]
}`

**Comment by Fruko** [comment] 2019-02-04 08:08
Hello Ken, 

thank you very much for your quick reply! I really appretiate it. I tried both examples that you descibred but none of them works for me

This is what my code looks like (not that if I load iframe url directly it works)
![image](https://user-images.githubusercontent.com/10186522/52196454-27b84200-285c-11e9-8fb9-b207726b8b7f.png)

the iframe has a proper name attribute
![image](https://user-images.githubusercontent.com/10186522/52196482-3d2d6c00-285c-11e9-8eac-81cf662fe3cb.png)

and the selector works aswell
![image](https://user-images.githubusercontent.com/10186522/52196509-5f26ee80-285c-11e9-915c-5d4da908cb46.png)

I believe that this is really only about settings the correct frame context to tagUI. Do you perhaps see any other reason apart from that multiline, why this does not work?

And again many thanks in advance for your help!

**Comment by kensoh** [comment] 2019-02-06 10:33
Interesting scenario! Copying @Aussiroth who is now maintaining the project. 2 other thoughts I have is, does the error message saying iframe not found show up? If not, it could be the selector being specified incorrectly. I see that the selector actually has a . in front to mean CSS selector by class, but in the TagUI script above there is no . which defaults to trying the best match from other ways such as XPath. Other than that you probably need to give @Aussiroth replication details to try out on the webpage to explore further.

**Comment by Fruko** [comment] 2019-02-12 14:30
Hello @kensoh there is no error, I checked both running with chrome flag and headless. Note that the script works perfectly fine if I start the script pointing to the iframe src directly so no iframes are involved.

However in our use-case we have to use iframes. I'm afraid that since it's a corporate page I am not allowed to give you an access. 

I can see in the CMD this error 
Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'
While TagUi log shows
ERROR - cannot find //*[@id="maincontent"]/lm-suite-home/div/div/div/div[44]/lm-simple-card

Also when I dump document outerHTML into a file it shows the iframe correctly with the proper name that I am then using to step in the frame step 

Could it maybe related to https and it's restrictions? Sth like
https://stackoverflow.com/questions/40980231/phantomjs-swithtoframe-does-not-work?fbclid=IwAR2pQVBK59vNX54etvWXBDUXam0x13VvzIuC_IUoaE_kh4U4m1Quk-icmqk

with difference that it would fail silently in TagUI?

Thanks in advance @Aussiroth  and @kensoh  for your help!

**Comment by Fruko** [comment] 2019-02-12 23:24
Hello,

I was able to reproduce our issue with open source stuff. I believe that this might be related to CORS
I created a simple html file that opens an iframe to Wikipedia
![image](https://user-images.githubusercontent.com/10186522/52674935-66698e80-2f25-11e9-9b1e-c030acda6ce8.png)

and my TagUI scripts looks like this
![image](https://user-images.githubusercontent.com/10186522/52674949-76816e00-2f25-11e9-9f36-399d712bb88b.png)

which results in an error 
![image](https://user-images.githubusercontent.com/10186522/52674974-8436f380-2f25-11e9-9ba8-3298326df10e.png)

even though

![image](https://user-images.githubusercontent.com/10186522/52675020-ac265700-2f25-11e9-9f65-11a6aaa24939.png)

**Comment by kensoh** [comment] 2019-02-13 03:50
Hi @Fruko this is good info, can you paste the raw HTML here so that I can test locally? Also let me know the exact options you use to invoke TagUI. For eg with chrome option or headless option or default no option (PhantomJS browser).

**Comment by Fruko** [comment] 2019-02-13 08:44
of course @kensoh 

```<!DOCTYPE html>
<html>
<head>
  <title>Tag UI test</title>
</head>
<body>
<iframe id="tagui" name="tagui" src="https://en.wikipedia.org/wiki/Infor" style="height: 100vh; width: 100vw"></iframe>
</body>
</html>
```
Thanks for reopening the issue!

**Comment by kensoh** [comment] 2019-02-16 07:10
Hi @Fruko thanks for all the replication details, learnt something new! I've tried your replication details and found that the issue is close to what you have discovered. TagUI uses the Iframe's contentDocument property in order to access the frame in a web document.

However, due to security restrictions this property can't be accessed if the domain of the frame is different from the parent webpage. For reference of this security limitation see here, I think it is the same across browsers -

https://www.w3schools.com/jsref/prop_frame_contentdocument.asp

I've not found any way to override this default Chrome web-browser behaviour. But if you find some ways to do so, you can share here. Have tested and debug in Chrome console and validate that a frame in another domain will return null when contentDocument property is called, but return a valid  node if the domain is the same.

Closing this issue, 2 alternatives I can think of that might work for your use case.

1. try running TagUI in the default mode without options (PhantomJS browser). I tried that on your replication html and it works. However PhantomJS is a pretty older browser and may not work correctly with your company internal webpages.

2. try finding out the exact URL of the frame. i've experienced a production implementation where my colleague find out the frame's URL and then use TagUI to access that frame directly by opening the URL directly (after logging in user credentials and stuffs). Simply specify the URL as part of the TagUI steps. It can also handle dynamic URLs if needed, for example below - 

```
https://`url_variable`
```

**Closed by kensoh** 2019-02-16 07:10 UTC
Labels: query

**Comment by Fruko** [comment] 2019-02-16 16:18
Hello @kensoh,

that's what I was afraid of, sadly we can't use the iframe src url directly. Anyway thank you very much for checking!

**Comment by mayurkagathara** [comment] 2019-03-26 10:33
@Fruko 
Hi Fruko,

I was facing the same kind of issue.
It was resolved using frame command.

In my scenario element X was inside iframe named Y.
**test 1:**
click X 
gave me error that element not found.
**test 2:**
frame Y{
click X
}
Worked :-)

FYI: I found this command in tagUI_editor.
