### ISSUE TITLE
Outlook appears differently in headless mode - by app's design, some ideas

### ISSUE THREAD

**Issue by trevorle97** [kelaberetiv/TagUI#919] opened 2021-01-27 22:23 UTC
Hi TagUI support team,

I have been able to create a script that would run normally with an open Chrome browser. This script basically is trying to select an email from Outlook.com based on the email's xpath - code example: click (xpath). However, when I tried to run the script headless (no browser) by using cmd: tagui c:\tagui\flows\samples\example.tag -headless, the script started to give me the error below,
ERROR - cannot find (xpath).

Would you please helping understand why this is an issue ? Is this a known problem yet ?

Thank you

**Comment by trevorle97** [comment] 2021-01-28 00:16
Something that I find out after I took a snapshot of the Outlook.com that was presented. Apparently the headless Chrome browser was using a Light version of Outlook.com (https://support.microsoft.com/en-us/office/learn-more-about-the-light-version-of-outlook-2aec8c2d-da48-4707-ba37-c800e1c284cd) due to outdated browser.

My script would need to run in the latest version of browser, would you mind letting me if it is possible to use the latest version of the browser while we are using the script headless ?

**Comment by kensoh** [comment] 2021-01-28 03:08
Hi @trevorle97, from your description it sounds like Outlook is able to detect that you are not using a normal browser, ie running Chrome using invisible mode. It might be possible to set the user agent for the Chrome session so escape detection. But over time that solution is brittle because Outlook team will pick up how to recognise such hacks and disables it as well.

For you use scenario, is it possible for you to write a separate flow for the Outlook lite? You can create a dummy file call a.tag and run `tagui a.tag -headless` to enter live mode in the invisible mode. From there test out the steps to write the flow.

```
live
```

You could use steps like below to see the web browser elements and DOM, but would be difficult for someone not experienced with HTML and webpage development.

```
read page to html
echo `html`
```

or 
```
save page to web.html
```

If there is some way to access Outlook lite directly, you can create that flow in the normal way first.

The issue is Outlook decided not to serve browsers like Chrome invisible mode, thus it serves the Lite version. So it's more of using automation in a way which isn't being supported by the app. Because normal user won't surf a webpage invisibly.

**Comment by kensoh** [comment] 2021-01-28 03:24
Adding on, more details and the train of thoughts - https://www.youtube.com/watch?v=lgFaQc6PLzg

**Comment by kensoh** [comment] 2021-02-18 17:43
Closing issue for now but do ping us if anything!

**Closed by kensoh** 2021-02-18 17:43 UTC
Labels: query
