### ISSUE TITLE
How to enter keyboard [ctrl][shift][delete] in TagUI

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#488] opened 2019-07-07 04:59 UTC
Hi @kensoh, with reference to issue #487, found that there's a keyboard shortcut to go direct to Chrome's "Clear Browser Data" menu by pressing `CTRL-Shift-Delete` (Windows) and `Command-Shift-Delete` (Mac)

Tried to do this in TagUI: `keyboard [ctrl][shift][delete]`
It didn't work

Also tried direct vision command:
```vision type(Key.DELETE, KeyModifier.CTRL + KeyModifier.SHIFT)```
and
```vision type(Key.DELETE, KeyModifier.CTRL | KeyModifier.SHIFT)```

Didn't work either.

Questions:
1) Can `keyboard` support 3-key combinations such as this (Ctrl-Shift-Del) or Ctrl-Shift-R (for chrome hard reload)?

2) How about using `vision type`? Do you know if it's possible?

**Comment by kensoh** [comment] 2019-07-07 20:12
Hi CK, 3-key combinations should work. It looks like for this case, for some reason, Chrome does not react to the 3-key combination sent by SikuliX. When I try below TagUI commands, it gets interpreted by SikuliX correctly in src/tagui.sikuli/tagui.log. However, only the [cmd][shift]4 works on my Mac. The [cmd][shift][delete] does not work even after I click on Chrome to focus on the web browser.

Can you try if `keyboard [ctrl][alt][delete]` works for you on Windows? If it works, may be an issue with how SikuliX 3-key combination interacts with Chrome. If doesn't work, maybe a bug at SikuliX with sending combinations involving delete or some specific keys.

```
[tagui] INPUT  - [32] keyboard [cmd][shift]4
[tagui] ACTION - keyboard [cmd][shift]4
[log] ( ⌘+⇧ )  TYPE "4"
[tagui] OUTPUT - [32] SUCCESS

[tagui] INPUT  - [33] keyboard [cmd][shift][delete]
[tagui] ACTION - keyboard [cmd][shift][delete]
[log] ( ⌘+⇧ )  TYPE "#DEL."
[tagui] OUTPUT - [33] SUCCESS
```

**Comment by ck81** [comment] 2019-07-08 02:31
> Can you try if `keyboard [ctrl][alt][delete]` works for you on Windows?

Just tried it.  It doesn't work on Windows 10.

**Comment by kensoh** [comment] 2019-07-08 05:36
Thanks CK for the details! Was about to raise an issue on [SikuliX's issues page](https://github.com/RaiMan/SikuliX1) but found on web that some users reported that ctrl+alt+del doesn't work on Windows 10.

Can you try below on your laptop and let me know the behaviour?

First try if pressing ctrl+alt+del manually opens up the lock screen or trigger some Windows action.

If yes, try below TagUI step to confirm that ctrl+alt+del doesn't do anything. Thanks in advance!

```
vision type(Key.DELETE, KeyModifier.CTRL + KeyModifier.ALT)
```

PS - I will also test this when I next have access to a Windows laptop

**Comment by ck81** [comment] 2019-07-09 08:38
> First try if pressing ctrl+alt+del manually opens up the lock screen or trigger some Windows action.

Yes, pressing ctrl+alt+del manually opens up the lock screen.

~~~
vision type(Key.DELETE, KeyModifier.CTRL + KeyModifier.ALT)
~~~

No actions.  It didn't activate the lock screen.

**Comment by kensoh** [comment] 2019-07-09 09:16
This may potentially be a bug upstream in SikuliX for some edge cases key combinations.

Have raised above issue (https://github.com/RaiMan/SikuliX1/issues/160) for further exploration. Thanks CK for raising!

**Comment by kensoh** [comment] 2019-07-10 19:28
Looks like both may be known issues.

First is the way Windows works - not allowing ctrl + alt + delete to trigger unless from real keyboard - https://bugs.launchpad.net/sikuli/+bug/548651

Second could be the known numlock issue with Java that may be fixed by turning off numlock -
https://bugs.launchpad.net/sikuli/+bug/894312
https://answers.launchpad.net/sikuli/+question/100368

SikuliX maintainer comments - https://github.com/RaiMan/SikuliX1/issues/160#issuecomment-509983858
My comments - https://github.com/RaiMan/SikuliX1/issues/160#issuecomment-510194088
(test numlock solution after unlocking borrowed laptop)

**Comment by kensoh** [comment] 2019-07-11 15:20
Hi CK, I've closed the upstream issue at SikuliX with below findings. For ctrl + alt + delete, from SikuliX maintainer it is because internally Windows/Java only allows trigger by pressing on a real keyboard. Workaround if need to do something like that would be to click visually on Start menu, then find and click on the lock screen menu.

For ctrl + shift + delete, it is due to the known issues above related to how Java when numlock is on interferes with some keystrokes. As the issue is further upstream in Java, it is inappropriate to handle in SikuliX or TagUI internally, thus closing this issue. Workaround is to check if numlock is on, and turn it off before invoking the key combination. The sample code is found below.

---

Hi Raimund,

I've tested on a Windows 10 laptop. For ctrl + shift + delete, I confirm that it is due to the known numlock issue with Java affecting shift key (https://bugs.launchpad.net/sikuli/+bug/894312 and https://answers.launchpad.net/sikuli/+question/100368). Below are my replication steps to confirm that it is due to the known issue.

Doing the following fails (I manually focus on Chrome browser while SikuliX waits) -
```
wait(5); type(Key.DELETE, KeyModifier.SHIFT + KeyModifier.CTRL)
```

Found out that numlock islockon status is True, and press numlock to turn it off -
```
print(Env.isLockOn(Key.NUM_LOCK))
type(Key.NUM_LOCK)
print(Env.isLockOn(Key.NUM_LOCK))
```

Doing the following works and opens up the Chrome delete browser history page -
```
wait(5); type(Key.DELETE, KeyModifier.SHIFT + KeyModifier.CTRL)
```

I'll close this issue now as both observations are known issues. Thanks Raimund!

**Closed by kensoh** 2019-07-11 15:20 UTC
Labels: bug
