### ISSUE TITLE
ERROR - jSON Parse error: Unexpected identifier "ERROR" (Using Moxie Studio)

### ISSUE THREAD

**Issue by 92Ashutosh** [kelaberetiv/TagUI#758] opened 2020-03-19 17:13 UTC
Hi All,

I just start learning Tagui So I faced one issue.I'm sharing my code, please suggest how to resolve this.

**Comment by kensoh** [comment] 2020-03-21 07:52
Closing this issue, duplicate of #759 which has more details

**Closed by kensoh** 2020-03-21 07:52 UTC
Labels: general
