### ISSUE TITLE
Session still exist even after logout (TagUI has its own separate Chrome user)

### ISSUE THREAD

**Issue by kurawadiprasanna** [kelaberetiv/TagUI#378] opened 2019-04-02 12:22 UTC
@kensoh, While executing the tagui scripts on chrome, i found an issue where chrome instance is still holding session information.

After logout and when i launch the application with new chrome browser instance, it directly navigates to the homepage without asking login credentials.

Please suggest

**Comment by kensoh** [comment] 2019-04-02 18:49
By design, TagUI will replicate the user actions. If there is no log out step, the next time webpage open it will be in logged in state. If there is logged out step, it should open with logout state.

By design, TagUI will use its own Chrome user in order not to mess up user's own session, and TagUI user session is different from the one user opens up on his browser manually.

Without replication steps, the above case may be TagUI user already log out but your manually open Chrome is still logged in. That's because they are 2 different user sessions.

**Comment by kensoh** [comment] 2019-04-04 12:57
Closing until further inputs as separate TagUI and user's Chrome sessions is by design.

**Closed by kensoh** 2019-04-04 12:57 UTC
Labels: query
