### ISSUE TITLE
run step is not working..

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#294] opened 2018-10-25 04:45 UTC
Hi,
    I have script to connect to mysql db. When I try to execute the flow, it is getting start, but becoming idle when it reaches to run step. Could you please share the necessary workaround?
FYI, script is...

_>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>_

sql_query = 'mysql _databasename_ --host=_hostname_ --user=xyz --password=\'abc\' -e "SELECT _coumn1_,_column2_ FROM _tablename_"'
dump sql_query to read_db
//run read_db
run _path to flow_/read_db

db_result = run_result.split('\n')
for row from 1 to db_result.length
{
        db_row = db_result[row-1].split('\t')
        echo db_row[0] ',' db_row[1]
}

_>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>_

**Comment by balwant-sd** [comment] 2018-10-31 06:20
My Script is
>>>>>>>>>>>>>>>>>>>>
```
sql_query = 'mysql temp_info --host=localhost --user=root password='' -e "SELECT name FROM emp"'
run '+sql_query+'
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
       db_row = db_result[row-1].split('\t')
       echo db_row[0] ',' db_row[1]
}
```
>>>>>>>>>>>>>>>>

when i try to execute flow it will show a error

```
SyntaxError: Unexpected string ' -e "SELECT name FROM emp"'

  phantomjs://code/sql_demo.js:1325 in injectJs
  phantomjs://code/bootstrap.js:456

```

Please Share Your Thoughts what should i do ??

**Comment by Aussiroth** [comment] 2018-10-31 07:02
Hi, for this, can you try writing the query as 
```sql_query = 'mysql temp_info --host=localhost --user=root password=\'\' -e "SELECT name FROM emp"'```
The single quotes need to be escaped, otherwise it will be interpreted as closing and reopening the string when translated into javascript code.

**Comment by balwant-sd** [comment] 2018-10-31 07:20
Yeah, It is running. 

But Now there is another issue. It will no fetch desired output. I am not showing full output, I will scip some lines.

```
START - automation started - Wed Oct 31 2018 12:44:50 GMT+0530 (IST)

run '+sql_query+'
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper,undefined
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.,undefined
,undefined
Oracle is a registered trademark of Oracle Corporation and/or its,undefined
affiliates. Other names may be trademarks of their respective,undefined
owners.,undefined
,undefined
Usage: mysql [OPTIONS] [database],undefined
  -?, --help          Display this help and exit.,undefined
  -I, --help          Synonym for -?,undefined
  --auto-rehash       Enable automatic rehashing. One doesn't need to use,undefined
                      'rehash' to get table and field completion, but startup,undefined
                      and reconnecting may take a longer time. Disable with,undefined
                      --disable-auto-rehash.,undefined
                      (Defaults to on; use --skip-auto-rehash to disable.),undefined
  -A, --no-auto-rehash ,undefined
                      No automatic rehashing. One has to use 'rehash' to get,undefined
                      table and field completion. This gives a quicker start of,undefined
                      mysql and disables rehashing on reconnect.,undefined
  --auto-vertical-output ,undefined
                      Automatically switch to vertical output mode if the,undefined
                      result is wider than the terminal width.,undefined
  -B, --batch         Don't use history file. Disable interactive behavior.,undefined
                      (Enables --silent.),undefined
  --bind-address=name IP address to bind to.,undefined
  --binary-as-hex     Print binary data as hex,undefined
  --character-sets-dir=name ,undefined
                      Directory for character set files.,undefined
  --column-type-info  Display column type information.,undefined
  -c, --comments      Preserve comments. Send comments to the server. The,undefined
                      default is --skip-comments (discard comments), enable,undefined
                      with --comments.,undefined
  -C, --compress      Use compression in server/client protocol.,undefined
named-commands                    FALSE,undefined
ignore-spaces                     FALSE,undefined
init-command                      (No default value),undefined
local-infile                      FALSE,undefined
no-beep                           FALSE,undefined
host                              localhost,undefined
html                              FALSE,undefined
xml                               FALSE,undefined
line-numbers                      TRUE,undefined
secure-auth                       TRUE,undefined
show-warnings                     FALSE,undefined
plugin-dir                        (No default value),undefined
default-auth                      (No default value),undefined
binary-mode                       FALSE,undefined
connect-expired-password          FALSE,undefined

FINISH - automation finished - 18.4s

```

Now what i should do to fetch detail from table.

**Comment by balwant-sd** [comment] 2018-10-31 08:00
Both Commands work Same. It does not fetch data from table

`sql_query = 'mysql temp_info --host=localhost --user=root password=\'\' -e "SELECT name FROM emp" '`

`sql_query = 'mysql temp_info --host=localhost --user=root password=\'\' '`

**Comment by Aussiroth** [comment] 2018-10-31 08:11
Hi, seems like the run command is able to successfully execute the command, but the problem is in the command line after logging into mysql. You probably need to add the use <database> into your command to use the correct database before querying.

**Comment by balwant-sd** [comment] 2018-10-31 09:17
Hi, Thanks For Your Assistance. Can You tell what should I do to get table data from database ?

**Comment by Aussiroth** [comment] 2018-10-31 10:09
Hi, maybe something like 
sql_query = 'mysql --host=localhost --user=root password=\'\' -e "use temp_info; SELECT name FROM emp" '
I am not very well versed in using mysql from the command line, so it would be better for you to google or look on mysql related tutorials for this.

**Comment by Aussiroth** [comment] 2018-10-31 10:11
@nsahithi 
Also, sorry but I realised my mistake here, you can perform the dump sql_query to a file, then send a run command to the file on macOS/linux to run the commands as a bash script, as you were doing previously. However, you will need to make sure that the file you have written to has the executable permissions set, otherwise the run step will fail.

**Closed by Aussiroth** 2018-10-31 10:11 UTC
Labels: query

**Comment by balwant-sd** [comment] 2018-10-31 11:22
> Hi, maybe something like
> sql_query = 'mysql --host=localhost --user=root password='' -e "use temp_info; SELECT name FROM emp" '
> I am not very well versed in using mysql from the command line, so it would be better for you to google or look on mysql related tutorials for this.

anything after ""sql_query = 'mysql --host=localhost --user=root password= "" does not work.

Ken Soh  Sir Where are you, Please help us @kensoh

**Comment by kensoh** [comment] 2018-11-01 06:52
Hi @nsahithi and @balwant-sd I have left AI Singapore and TagUI is in good hands of Alvin @Aussiroth - what Alvin mentioned in above message is correct, TagUI run step is used to run mysql command to query database and return results.

For Linux, macOS, you first have to create a file with the mysql command to run to return the results. Then chmod 700 to enable it to have run permissions. Then you can try running from command prompt `./your_file` to try running your mysql query script to see if it returns the results you want.

If your mysql script does not work as expected, I'm afraid you will have to find other resources online on mysql and database, as this is beyond the scope of how to use TagUI, and there are better resources and tutorials on how to use mysql command to read from database.

If your mysql script works, then you can use run step `run your_file` from TagUI to run that script.
