### ISSUE TITLE
Parallel runs not supported by design - try using hack to speed up 20X

### ISSUE THREAD

**Issue by DataLeon** [kelaberetiv/TagUI#797] opened 2020-05-01 06:06 UTC
Hi,

First off, Tagui is a really fantastic tool that has worked wonders for me.

My current problem is that I am trying to run different python scripts that uses tagui at the same time to reduce the time taken to run all.

However, when I try to "init()" rpa in another python script, the existing script that is running the rpa is stopped and a new google chrome window opens.

The problem persists even when i am using like a remote desktop, whereby i am logged in to several different accounts, but still within the same desktop, whereby when i try to init the python tagui in one account, and when i try to init it in another account (its as if two different persons is running the python tagui in their own accounts within the remote desktop),  the previous tagui init is stopped, and then the other accounts tagui init is started.

Is there any way to run different python tagui scripts at the same time within like the same remote desktop? 

I have tried creating a completely new python environment so that the tagui package installed is separated from other python environments, but I am still unable to run more than 1 tagui python scripts.

I know using javascript will work, but what about for when tagui in python?

Edit: This happens in both an ubuntu and windows remote desktop

**Comment by kensoh** [comment] 2020-05-02 02:45
Hi @DataLeon thanks for sharing your feedback!

Normally for RPA for Python, raise issues there https://github.com/tebelorg/RPA-Python/issues because these are separate project with different problems, and RPA for Python is a project I maintain on my own, while TagUI is maintained by AI Singapore.

But this case the bottleneck is at the upstream TagUI project. Yes it is by designed to run only a single instance on a computer. Same for the RPA for Python tool. The goal is to automate a human user actions on apps whether for business or personal use cases.

By designing it as a single instance, the tool can prioritise on being stable and robust (eg running 10h+ overnight automation jobs without problem), instead of having the ability to run in parallel, which serves the needs of a smaller group of users at the expense of resiliency of use cases of most users.

There are ways to do parallel, but it takes a lot of config efforts for you. You'll have to make sure each instance you want -

1. the TagUI is installed at different folders. This is because the communication channel btw TagUI and Chrome is within that folder. Running multiple threads will surely step onto each other.

2. need to make sure different user accounts are used to run the different instances, and ensure that one user account has no access to processes in other one. Otherwise, when automation exits, it could kill processes in other user accounts.

3. to do 1 and 2 well, if you are using RPA for Python, will need you to hack different copies of the source file to point to the different instances, plus probably you want to write something that overall will invoke the jobs to run on the different instances.

So.. Very troublesome.

**Comment by kensoh** [comment] 2020-05-02 02:48
However, if your goal is to only reduce the run-time, you could try some hacks in below link.

By reducing the delay time (by design) in communications btw TagUI and Chrome from 200ms to 0ms, and by changing typing behaviour to type all string at one go instead of character by character, the RPA Challenge example of filling many fields run over 20X faster. From 2min before the hack to under 5 seconds after the hack.

However, most websites are not designed for such superhuman speed actions by users, so you might need to moderate a bit to find a good balance that works for your target websites.

https://github.com/kelaberetiv/TagUI/issues/790

**Comment by kensoh** [comment] 2020-05-02 02:57
Last but still important, one of the reasons for not supporting parallel runs is a user can stretch the rate of access to a website to a very high rate. This usually is a recipe for disaster, for mainstream tech giant websites.

They are likely to detect automation at work here and perhaps block your user ID, laptop IP, or company network IP range. And understandably so because their business revolve around the data they have built up. So.. be careful in trying to run at the fastest speed possible.

The real bottleneck often is not the technical reasons like run speed or parallel runs, but anti-automation mechanisms on the target websites that you are doing automation on.

**Comment by DataLeon** [comment] 2020-05-03 13:25
Hi Ken,

Thank you so much for the advice!

I have checked out the site where you mentioned the changes that you made to speed up the communication between chrome and tagui and I have tested it out, but i notice one thing that changes after I made the changes, in which when I am using r.type("key[enter]"), it does not enter at anymore.

Is there any additional changes that I can add to enable back the "[enter]" mechanism but still keep all the changes made above?

Adding the comment here for others to see, as it has really speed things up!
https://github.com/tebelorg/RPA-Python/issues/120#issuecomment-610532082

**Comment by kensoh** [comment] 2020-05-03 19:05
You're welcome Leon!

I see, yes `key[enter]` will get mapped to `key\r`. But telling Chrome to type in `key\r` directly will not work. An idea is to break up the string. Can you try if using `r.type('identifier', 'key'); r.type('identifier', '[enter]');` works for you use scenario?

**Comment by DataLeon** [comment] 2020-05-04 01:21
Hi Ken,

I tried the solution you mentioned, but it did not work. However, I was able to find a work around it.

Thank you!

Also, I would like to inquiry more about what you said in an earlier reply:


> Hi @DataLeon thanks for sharing your feedback!
> 
> Normally for RPA for Python, raise issues there https://github.com/tebelorg/RPA-Python/issues because these are separate project with different problems, and RPA for Python is a project I maintain on my own, while TagUI is maintained by AI Singapore.
> 
> But this case the bottleneck is at the upstream TagUI project. Yes it is by designed to run only a single instance on a computer. Same for the RPA for Python tool. The goal is to automate a human user actions on apps whether for business or personal use cases.
> 
> By designing it as a single instance, the tool can prioritise on being stable and robust (eg running 10h+ overnight automation jobs without problem), instead of having the ability to run in parallel, which serves the needs of a smaller group of users at the expense of resiliency of use cases of most users.
> 
> There are ways to do parallel, but it takes a lot of config efforts for you. You'll have to make sure each instance you want -
> 
> 1. the TagUI is installed at different folders. This is because the communication channel btw TagUI and Chrome is within that folder. Running multiple threads will surely step onto each other.
> 2. need to make sure different user accounts are used to run the different instances, and ensure that one user account has no access to processes in other one. Otherwise, when automation exits, it could kill processes in other user accounts.
> 3. to do 1 and 2 well, if you are using RPA for Python, will need you to hack different copies of the source file to point to the different instances, plus probably you want to write something that overall will invoke the jobs to run on the different instances.
> 
> So.. Very troublesome.

As since different users might like to use tagui python as well within the remote desktop, I wondering how would one go about doing this in a windows remote desktop? Since regarding your two points:
1. For windows, Tagui is installed in "APPDATA", which different users have their own, so is that already considered different folders?
2. Regarding this, how would one go about ensuring that a different instances is run in different user accounts? Does it have to be a completely new python environment, or are there other processes that have to be run on a completely different instances?

Thank you so much for your help! And so sorry for the troublesome questions!

**Comment by kensoh** [comment] 2020-05-04 03:00
Oh great! Can you share more on your workaround for the issue of typing `key[enter]`?

1. That's true, that should already be in different folder. The Python interpreter should have no difference installed to all users or by individual user. When the RPA for Python package is run, it should download and install TagUI to the user's own APPDATA folder.

2. I haven't tested on this before. In theory, it will be hard to imagine that one user account can kill processes running in another user account. Unless there is some bad configuration of the OS. You can try running and make sure each automation job is run as the respective normal user account and NOT the admin account. See if that helps prevents user A from killing user B processes.

No probs! We can figure out on the best solution together 👍🏻

**Comment by DataLeon** [comment] 2020-05-06 02:31
Thank you so much for the advice!

The workaround was simply a r.click("idenitfier button") to sort of submit what i have written. The simplest hack around i could find.

As to your point in point 2, one user account CAN KILL another process in another user account, which is essentially what happen when i tried to run tagui in two different accounts. Whichever account that ran the tagui init() command later would kill the previous account tagui init() chrome. I have seen it happen simultaneously as I ran the init() command in one account, and I can see the previous chrome window that was opened in the other account close, and the python started running into error.

I was trying to like install chrome separately in separate account so that it does not point to the same chrome instance in the remote desktop, but it seems that is not doable for google chrome.

If you have any solution, I will greatly appreciate it!

**Comment by kensoh** [comment] 2020-05-21 16:45
I see, it sounds like computer environment setup, because apps installed for 1 user and running in 1 user account, shouldn't be able to be killed by some other user account.

User B should not have write and kill access to processes running in User A. Though I can't comment further because I have not tried setting up separate accounts to run in parallel before.

**Comment by kensoh** [comment] 2020-05-30 13:50
Closing this issue for now.

My part-time contract with AI Singapore is ending and I'll not be renewing for time being. My colleague @siowyisheng will help support TagUI users with issues they raise on GitHub.

**Closed by kensoh** 2020-05-30 13:50 UTC
Labels: query
