### ISSUE TITLE
Desktop automation initialisation takes too long - try other ways

### ISSUE THREAD

**Issue by SkyDB** [kelaberetiv/TagUI#741] opened 2020-02-28 19:25 UTC
I used the TagUI (package installation for Win, use "tagui try.txt quiet speed" to run) on the workplace PC for desktop automation, however, every time when running the process, the initialization time takes ~1min. Is there any way to short this time? Or just initial TagUI once? like running in python enviro, not necessary to initial every time before running the process.

**Comment by kensoh** [comment] 2020-02-29 02:18
1. Are you using computer vision / visual automation steps in your automation workflow?

If yes, then OpenCV (for computer vision) and Tesseract (for OCR image-to-text) is required to be loaded and the engines requires around 10-20 seconds to load on older laptops. For current laptops it should be faster, and definitely taking 1 minute to load is not normal.

2. Can you try running the same workflow on another laptop to see if it takes as long to load? If the one that is slow is your work laptop, try using your personal laptop to see if it is faster. It could be some network policy or application policy on work laptop that slows down initialisation.

**Comment by SkyDB** [comment] 2020-02-29 02:52
> 1. Are you using computer vision / visual automation steps in your automation workflow?
> 
> If yes, then OpenCV (for computer vision) and Tesseract (for OCR image-to-text) is required to be loaded and the engines requires around 10-20 seconds to load on older laptops. For current laptops it should be faster, and definitely taking 1 minute to load is not normal.
> 
> 1. Can you try running the same workflow on another laptop to see if it takes as long to load?
> 
> If the one that is slow is your work laptop, try using your personal laptop to see if it is faster. It could be some network policy or application policy on work laptop that slows down initialisation.

Thanks for the quick reply. 
1. Yes because I use image for the cursor to locate position. The PC is a bit old, but it directly connect to the operating machine. The purpose is to save some routine operations for operators.
2. Running on personal laptop is faster, I would like to seek any opportunity to initialization only once to load opencv and engine to save time?

**Comment by kensoh** [comment] 2020-02-29 03:31
I see.. Thanks for sharing the context. The engine is designed to initialise for each new run instead of running once and persist in memory. This is by design, so that running 100 times it will still be robust and working properly. Because each time TagUI runs, the engines are initialised, used, and killed. So each time it will be fresh and work at the best state.

Running persistently may introduce problems with memory over time for the SikuliX engine and risk the quality of automation working perfectly, so there isn't a way to do that in TagUI and no plans to implement that way.

From your scenario, there are some ideas that you can try to see if they work for you use case -

1. try scheduling the automation jobs so that they are called by task schedule 1 or 2 minutes before when they are needed. So the delay becomes not a problem anymore.

2. try writing your TagUI automation workflow so that it keep looping and perform the automation when it is needed. From some other trigger for example a change in a text file content. For example below (note that infinity is set to 1024 by default) -

```
for n from 1 to infinity
{
    load trigger_file.txt to trigger_text
    if trigger_text contains 'some string'
    {
        // do what you need in the automation
    }
    wait 60 seconds
}

**Comment by SkyDB** [comment] 2020-02-29 03:56
> I see.. Thanks for sharing the context. The engine is designed to initialise for each new run instead of running once and persist in memory. This is by design, so that running 100 times it will still be robust and working properly. Because each time TagUI runs, the engines are initialised, used, and killed. So each time it will be fresh and work at the best state.
> 
> Running persistently may introduce problems with memory over time for the SikuliX engine and risk the quality of automation working perfectly, so there isn't a way to do that in TagUI and no plans to implement that way.
> 
> From your scenario, there are some ideas that you can try to see if they work for you use case -
> 
> 1. try scheduling the automation jobs so that they are called by task schedule 1 or 2 minutes before when they are needed. So the delay becomes not a problem anymore.
> 2. try writing your TagUI automation workflow so that it keep looping and perform the automation when it is needed. From some other trigger for example a change in a text file content. For example below (note that infinity is set to 1024 by default) -
> 
> ```
> for n from 1 to infinity
> {
>     load trigger_file.txt to trigger_text
>     if trigger_text contains 'some string'
>     {
>         // do what you need in the automation
>     }
>     wait 60 seconds
> }
> ```

Awesome, thank you, will try.

**Comment by kensoh** [comment] 2020-03-02 09:13
I'll close this issue for now but feel free to add new inputs and reopen the issue!

**Closed by kensoh** 2020-03-02 09:13 UTC
Labels: general
