### ISSUE TITLE
Document return null - usage issue dom step can be used to return text not objects

### ISSUE THREAD

**Issue by cheehau** [kelaberetiv/TagUI#1041] opened 2021-05-25 23:04 UTC
Hi @kensoh 

Thanks for this awesome library. I have the below code snippet.

https://www.yahoo.com/
dom return document
dump `dom_result` to result.json

the result.json is always null.

Is this behavior correct?

**Comment by kensoh** [comment] 2021-05-26 15:53
Hi @cheehau you can't actually return document as an object from Chrome's JavaScript environment to TagUI's JavaScript environment because they are 2 different environments and JavaScript engines. Transferring back text is ok.

For example, below works. It is also possible to transfer back more complicated data perhaps by JSON string and then convert from JSON string back to JavaScript object. But in normal use cases, there isn't a need to do things using `dom`. Can you tell me more about what you want to do and I see if using TagUI steps like `read page` or helper functions like `text()` can do it?

```
https://www.yahoo.com/
dom return document.querySelector('#Header').innerText
echo `dom_result`
```

```
Yahoo Home
Search query
Sign in
 Mail
Mail
Mail
News
News
Finance
Finance
Celebrity
Celebrity
Lifestyle
Lifestyle
TV
TV
Shopping
Shopping
Esports
Esports
```

**Comment by cheehau** [comment] 2021-05-31 02:01
Hi,

Cool. @kensoh thanks for the explanation, I will try if it fits my use case.

btw kudos to this awesome project

**Comment by cheehau** [comment] 2021-05-31 02:04
Just another question @kensoh 

I recently move from macOS to windows, in macOS it is working correct, however in windows, it stuck in this screen.

![image](https://user-images.githubusercontent.com/9443775/120129913-82c58e00-c1f7-11eb-99d3-50e18f812033.png)

**Comment by kensoh** [comment] 2021-05-31 03:44
Welcome @cheehau, thanks for sharing your appreciation!

Sure, I've replied your Telegram message, let's see how to solve the issue.

Also, adding on, I saw that you have programming background. In that case, the Python version of TagUI may be easier to use for you vs the human language version. But it depends on what you are trying to do (data-processing heavy or making use of Python packages the Python one will be better, doing RPA so that your non-technical colleagues can use then the human language one will be better) - https://github.com/tebelorg/RPA-Python

**Comment by cheehau** [comment] 2021-06-02 04:12
Hi, @kensoh

Din know there is a python available. A good addition for me. thanks

I took a look, I am not sure if it is just happening on my end only.
I do believe there is something wrong with PHP 5.6.30 on windows, especially on the file_exist function. I have no other machine to test this.

I replace the php with  7.3.28 and it looks working so far, but believe there might be breaking change.

Just wonder how do you manage your php dependancy currently in the release build?

**Comment by kensoh** [comment] 2021-06-03 06:32
Hi Chee Hau, can you tell me more about the file_exist() function and how you have the clue that the function in PHP 5 has a problem on your system?

For Windows, because it does not have PHP built-in, I will package a PHP 5 as part of the TagUI_Windows.zip. This will allow TagUI to run without having to make separate installation. Normally, I won't upgrade to new version unless it is necessary, because it might create compatibility issues and likely introduce new run issues due to dependencies. These type of issues will take months to finally fix, as users report and I iterate on the solution.

**Comment by cheehau** [comment] 2021-06-03 06:59
Hi,

I use the follow php snippet to check

<?php
if ( file_exists(__FILE__) ){
  echo 'it works';
} else {
  echo 'it does not work';
}

**Comment by cheehau** [comment] 2021-06-03 07:00
![image](https://user-images.githubusercontent.com/9443775/120601342-65552600-c47c-11eb-80b3-ad327b76871d.png)

**Comment by cheehau** [comment] 2021-06-03 07:06
the php folder is the one I replace with php 7.x.x.  Agree that it will be very hectic to replace the PHP, definitely need to prove that this happens in a lot of window machine before deciding to roll that out.

So I am not sure if most of the user is using MacOS. Or mine is just the isolated Case =(....

I also try out the RPA python today which I realise it depends on the tagui also.. LOL... I need to manually replace the PHP in the roaming folder... just saying....

Anyway I can live with it if mine is the isolated case, then it is just bad luck for me then.

Thanks so much.

**Comment by kensoh** [comment] 2021-06-03 07:45
I see.. for MacOS, TagUI will use the PHP that comes installed with Mac.

Can you tell me more on file_exist()? There must some reason you are zooming down to that function. Maybe I can check what is breaking and try to understand why it's breaking on your Windows system. I tried on the PHP v5.6.30 that comes with TagUI for Windows and the test php file you wrote above shows 'it works' output correctly.

Likely a rare issue probably due to environment (because no one has raised this before amongst tens of thousands of users), but still good to figure out the root cause. Overwhelmingly most users are on Windows.

Yes RPA for Python is a wrapper around a forked version of TagUI optimised for the Python package.

**Comment by cheehau** [comment] 2021-06-03 08:21
Hi @kensoh 

so when I start any flow, it will fail at this line https://github.com/kelaberetiv/TagUI/blob/master/src/tagui_parse.php#L16 which file_exists always return false.

oh shucks, then it looks like it is happening on my env only...

**Comment by kensoh** [comment] 2021-06-03 09:27
Hi Chee Hau,

I found some links on the file_exists() function which may be related and some ideas to explore if you have some time -

1. Using `clearstatcache()` to clear the cache -
https://stackoverflow.com/questions/6930150/file-exists-returns-false-but-the-file-does-exist

2. Some potential reason why file_exists() return False even when file is there -http://man.hubwiz.com/docset/PHP.docset/Contents/Resources/Documents/php.net/manual/en/function.file-exists.html

3. Can you try putting your tagui to c:\tagui (to eliminate a possible cause maybe for some strange reason a folder name has a space and broke the PHP code

4. inside the https://github.com/kelaberetiv/TagUI/blob/master/src/tagui_parse.php#L16 can you add `echo $script;` and run TagUI to see what is the file path and filename? Maybe there is clue why the file does not exist

**Comment by kensoh** [comment] 2021-06-22 02:42
Closing for now until further inputs

**Closed by kensoh** 2021-06-22 02:42 UTC
Labels: query

**Comment by bcpeinhardt** [comment] 2021-09-08 13:47
Hello!
I am running into issues trying to get the value of a textarea via the dom_result.
```
dom return document.querySelector('.mce-textbox').value
echo `dom_result`
```
Will output
```
null
```
But in the console of the browser it displays.
![example_console_output](https://user-images.githubusercontent.com/61021968/132521190-2391f675-f84f-41c6-91ec-e64d0007bdf1.png)

I need to pull the value from that textarea and type it into another textarea via popup. Any advice?

**Comment by kensoh** [comment] 2021-09-08 15:41
I'm afraid I can't tell why without having a look at your website. Following works for me -

```
https://tebel.org/gist/about_tebel
dom return document.querySelector('#file-about_tebel-LC2').textContent
echo `dom_result`
```

**Comment by bcpeinhardt** [comment] 2021-09-09 04:40
I have done my best to replicate the issue on public sites. I would like to copy html from an mce editor on a popup page then write it to a textarea on the original page. Here are various attempts at that:
```
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea

dom document.body.insertAdjacentHTML("afterbegin","<a href='https://www.tiny.cloud/docs/demo/pageembed/' target='_blank' id='myLink'>myLink</a>");
click myLink

popup tiny
{
// I want to copy this html to the textarea on the page before
click //button[@title="Source code"]
wait 1
// I want to copy this html

// null
dom return driver.querySelector('textarea.tox-textarea').value
echo `dom_result`

//null
dom return driver.querySelector('textarea.tox-textarea').innerHTML
echo `dom_result`

//null
dom return driver.querySelector('textarea.tox-textarea').textContent
echo `dom_result`

// Keyboard step blocks
// click //textarea[@class="tox-textarea"]
// keyboard [ctrl]a
// keyboard [ctrl]c

read //textarea[@class="tox-textarea"] to htmlstring
echo `htmlstring`
}

// Doesn't write to textarea
type w3review as [clear]`htmlstring`
live
```

**Comment by bcpeinhardt** [comment] 2021-09-09 04:47
I want to copy the "source" from the editor on https://www.tiny.cloud/docs/demo/pageembed/ to the textarea on https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea

**Comment by bcpeinhardt** [comment] 2021-09-09 04:55
On the company sites:

Source:
![html_source](https://user-images.githubusercontent.com/61021968/132624669-5c60fe26-143f-4c0a-a7a4-df6deb0c0d06.png)

Destination:
![html_destination](https://user-images.githubusercontent.com/61021968/132624702-8536f074-532f-46b4-96ca-ddfb1c0dff24.png)

source html:
```
<textarea id="mceu_28" hidefocus="1" spellcheck="false" class="mce-textbox mce-multiline mce-abs-layout-item mce-first mce-last" style="direction: ltr; text-align: left; left: 20px; top: 20px; width: 590px; height: 490px;"></textarea>
```

destination html:
```
<textarea name="htmlOriginalBody" helpmsg="" id="defaultHtmlBody" style="width: 99%; height: 552px; visibility: visible;" class="editor tagInsertable content" spellcheck="false"></textarea>
```

**Comment by kensoh** [comment] 2021-09-09 05:29
Can you tell more what is the error?

Is the error after reading the value from dom there is no value, or the error is writing the variable to the original window?

If dom returns no value, try visiting the page directly instead of using popup step. Using popup step may not work for more complicated actions like sending a lot of data back with dom step.

If all else fails, just use visual automation and keyboard step to select and copy out the text, then paste it in original window.

**Comment by bcpeinhardt** [comment] 2021-09-09 06:13
It works when I visit directly instead of doing the popup! Also the quotes print normally instead of as unicode haha. Thank you so much!

**Comment by kensoh** [comment] 2021-09-09 07:08
Oh great! Yes there is some limitation of popup step, due to the way Chrome sends data back for new tabs.
