### ISSUE TITLE
Spawn multiple tagui instances with same flow

### ISSUE THREAD

**Issue by terrygoldman** [kelaberetiv/TagUI#85] opened 2018-03-06 23:13 UTC
Hi,
I was wondering if there is a way to spawn a tagui instance that use the same flow. 

And have the ability to specify the rows in the database file, such as the first instance of tagui uses even rows of the database file, and the second instance of tagui uses the odd rows of the database table. 

Or you could specify the first 10 rows to the first instance, rows 11-20 to the second instance, so on a so forth. 

With this feature, I can run flow with a 100 rows/test in with the same flow in parallel, thus I can optimized the overall execution time of the flow.

Possible? 

BR,
Terry

**Comment by kensoh** [comment] 2018-03-07 04:27
Hi Terry,

Each TagUI instance runs on its own, but you can try running separate instances by calling from bash script or windows batch file. For the data tables, you can split up into the separate files before triggering the multiple instances. Ideally you run those from separate duplicated directories, so that the temporary files generated don't mess with each other. 

Running multiple instances from same installation might work for some use cases (eg default PhantomJS invisible browser instead of Chrome browser). System resources / capacity is also a consideration as each instance literally runs a browser instance and has its own website CPU load.

In practice, I actually try to slow down the execution, for example adding a 3 second delay by default (can be overwritten by speed option) between different iterations. This helps to slow down the automation to a more human-load level instead of exceeding rate limits of websites which may block access to your IP for doing the automation at scale.

**Comment by kensoh** [comment] 2018-03-08 06:39
Closing the issue for now, but do let me know your thoughts!

At the moment, by design TagUI doesn't automatically break up a huge datatable with many rows and run the automation in parallel. In some cases it might work by user by splitting and running separate instances. Above comment has more details how to implement.

**Closed by kensoh** 2018-03-08 06:39 UTC
Labels: query
