### ISSUE TITLE
Error locating button inside an iframe

### ISSUE THREAD

**Issue by johnreedak** [kelaberetiv/TagUI#870] opened 2020-09-23 18:50 UTC
I'm working on a flow that collects rfp information from various websites. I've been trying to figure out how to click the "I Agree" button that is located inside an iframe. I'm at a loss of what to do.

Here is the website: https://www.asdk12.org/purchasing/bidlist/

Here is the iframe and button I want to click:
![Capture](https://user-images.githubusercontent.com/69942326/94056287-92e4be00-fd8a-11ea-8933-b7c92e47bb9f.JPG)

**Comment by siowyisheng** [comment] 2020-09-23 22:14
Hi. Check out the `iframe` step in the documentation.

**Comment by johnreedak** [comment] 2020-09-23 22:32
Could you point me where specifically? I haven't been able to find anything regarding iframe.
![Capture1](https://user-images.githubusercontent.com/69942326/94076459-9b002600-fda9-11ea-9c57-81444bd349a9.JPG)

Thanks

**Comment by siowyisheng** [comment] 2020-09-23 23:14
My bad. The step is called `frame`.

https://tagui.readthedocs.io/en/latest/reference.html#frame

**Comment by johnreedak** [comment] 2020-09-24 00:26
Ok, I'll give that a try and let you know if I'm still having problems after. Thanks.

**Comment by johnreedak** [comment] 2020-09-30 18:37
I tried using the frame step but still can't get it to work. Would you mind taking a look at my code and see if I'm doing it right? The website is: https://www.asdk12.org/purchasing/bidlist/


https://www.asdk12.org/purchasing/bidlist/
title = ''
link = ''
closing = ''
status = ''

wait 10

frame //*[@id="module-content-11714"]/div/div[2]/div[1]/span/p/iframe
    click //*[@id="btnAgree"]

**Comment by kensoh** [comment] 2020-11-29 03:18
Sorry John, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

This is indeed a tricky scenario and I have found the root cause after some deep debugging. In summary, Chrome blocks programmatic access to the frame contents, because it is actually hosted in another subdomain URL that is different from the parent web page.

![error](https://user-images.githubusercontent.com/10379601/100530939-3fcc3300-3233-11eb-8137-def0c32f4c3d.png)

To get to this stage, I use the TagUI line `dom document.querySelector('[title="current bid list"]').setAttribute("id", "terms_of_use");` to insert an ID to the frame, so that it can be accessed with `frame terms_of_use` step. But from debugging in Chrome console and TagUI-Chrome integration logs, it turns out that the frame contents are blocked by Chrome due to being in a different subdomain.

This is still automatable by using visual automation. You can do something like below -
```
https://www.asdk12.org/purchasing/bidlist

// click on chrome to ensure browser is active and in foreground
click chrome_icon.png

// use keyboard step to press down number of times as required to make the button visible
keyboard [down][down][down]

// take a snapshot of the button and use as the parameter to click on
click i_agree_button.png
```

There are also other creative ideas like doing a `keyboard [ctrl]f`, `keyboard i agree[enter]` to make the web page jump to the part you want to click on, before doing `click i_agree_button.png`. The guideline is try to map out how you will do it manually and convert the sequence of manual steps into the TagUI steps.

Closing issue for now but please lemme know if you have any input or question.

**Closed by kensoh** 2020-11-29 03:18 UTC
