### ISSUE TITLE
Warning message on web page - complex scenario no easy solution

### ISSUE THREAD

**Issue by Fry115** [kelaberetiv/TagUI#586] opened 2019-10-08 14:52 UTC
Hi Ken,

I need your help once again, I have a button that saves information, the issue is that said button at the time of clicking stops the automation until it accepts a warning, I have not managed to get tagUI to click on the warning, do you know any way to jump or manage to click on that warning?

Button Code:
![image](https://user-images.githubusercontent.com/54330118/66406219-a81ddc80-e9c1-11e9-92d0-cdb104ddc8d1.png)

 Warning message:
![image](https://user-images.githubusercontent.com/54330118/66406275-c08df700-e9c1-11e9-8eb1-bd1b7c0ea10f.png)

Greetings.

**Comment by kensoh** [comment] 2019-10-09 03:57
Hi @Fry115 some ideas you can try -

1. `click //*[@class="boton"]` - but this may not work if it is not unique enough, so try 2
2. click (//*[@class="boton"])[n] - try in Chrome debugging console where n is that button
3. dom doContinuar() - this tries to run the JavaScript function directly in Chrome browser
4. the last resort is foolproof way by using visual automation and computer vision to click. You just need to supply image of the button for eg `click aceptar.png`. But there is overhead of around 10 seconds during start-up to load the OpenCV computer vision engine. https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by Fry115** [comment] 2019-10-09 18:34
Hi Ken,

Currently, if I click on the “save” button, what happens is that once I click on the “save” button, I get a window that stops all automation, I can't even click on the "aceptar" button with visual mode , simply tagui does not perform any action after clicking the "save" button

Greetings.

**Comment by kensoh** [comment] 2019-10-10 01:31
Hi @Fry115 oh I get it now... This one is really tough. What happens is the popup window will block execution control from going back to TagUI... It is not impossible to solve this, but very challenging.

Something you can try is to combine 2 TagUI scripts and installation of TagUI in 2 different directories. Script 1 is run the normal web automation sequence. Script 2 is just using visual automation to click the accept button.

Then finally combine the 2 scripts with a Windows batch file or Linux / macOS bash script. And call script 1 to be run in the background so that it does not block script 2.

This is a challenging scenario, and so far I have not found the best solution to this. The issue is control does not return to TagUI as long as the popup window is not acknowledged by user. But without the process control being returned back to TagUI, it cannot do the automation step of clicking on the popup window button.

**Comment by Fry115** [comment] 2019-10-11 14:58
Thank you, I will try and tell you how it works.

**Comment by kensoh** [comment] 2019-10-18 05:17
Closing issue for now until further inputs!

**Closed by kensoh** 2019-10-18 05:17 UTC
Labels: query

**Comment by Fry115** [comment] 2019-11-20 15:03
Hi Ken,
I answer this thread so as not to open another one, as I told you, the instruction had worked for me:

dom doContinuar()

But they updated the page and added everything with “iframes” so my robot stopped working… I have managed to automate almost everything with TagUI (thanks for the amazing tool) but I have not managed to click on the “Record” button
My question is what you mean by this:

![image](https://user-images.githubusercontent.com/54330118/69250023-af720180-0b8d-11ea-98ef-59fcf5587446.png)

 
I don't understand how to get to the value of n ...
Regards.

**Comment by kensoh** [comment] 2019-11-20 15:09
Ic.. If there is iframe you can try the frame step to see if that works by giving the frame id or name.

frame id_or_name
{
step 1
step 2
step 3..
}

For `click (//*[@class="boton"])[n]`, you go to Chrome inspector, search for the identifer `//*[@class="boton"]`. Then you check which one is it. Because there can be many web elements with the same class. If it is the 3rd occurance then you try `click (//*[@class="boton"])[3]`

**Comment by Fry115** [comment] 2019-11-20 15:56
I understand, 
I discovered with your help the value of n... but i can read the button but not click...
![image](https://user-images.githubusercontent.com/54330118/69254253-ba7c6000-0b94-11ea-9faa-5f3f03fe8188.png)

![image](https://user-images.githubusercontent.com/54330118/69254258-bea87d80-0b94-11ea-90e0-75fa82d94295.png)

TAgUi doesn't throw me any error, just doesn't click ... weird

**Comment by kensoh** [comment] 2019-11-20 16:36
Ic.. You can try using visual automation to click on the button, as a workaround. Alternatively, download the cutting edge release from below link and steps. There is new changes to work with some updates in Chrome. Otherwise clicking within a frame will not work correctly.

https://github.com/kelaberetiv/TagUI#set-up
