### ISSUE TITLE
Chrome has to be opened only when the step reaches the web automation

### ISSUE THREAD

**Issue by umakattula** [kelaberetiv/TagUI#401] opened 2019-04-12 15:07 UTC
Hi,

I am raising the older issue #293 which is closed previously. When the execution starts, chrome is opening before the flow (At the very first step)  even when web automation is at the end of process.Can it be fixed/is fixed.

If not, can we have some guidance to fix it as well as the places that may affect while fixing it.

Thanks in advance,
Umasrinivas

**Comment by kensoh** [comment] 2019-04-17 01:47
Hi Umasrinivas, by design TagUI will invoke Chrome browser visible mode if chrome option is used, or Chrome browser invisible mode if headless option is used. The architecture of TagUI does not support invoking browser halfway because it is necessary to invoke via shell and connect to it via web socket to communicate and control Chrome.

Alternatively, if you are using visual automation to visually control Chrome, then it is possible to invoke halfway, because there is no web socket connection to directly control Chrome. But you will be limited to interaction with Chrome only using computer vision and no access to the web DOM layer through element IDs and so on. More details here -

https://github.com/kelaberetiv/TagUI#visual-automation

The last alternative will be invoking another TagUI script using run step. But it may involve installing a separate TagUI installation to make sure it does not interfere with parent script. This may take you troubleshooting time to setup and may still not work. Because invoking TagUI without Chrome and invoking Chrome in a sub-script is not a use case tested in TagUI.

**Closed by kensoh** 2019-04-17 01:47 UTC

**Comment by kensoh** [comment] 2019-04-17 01:51
Adding on, you can also try using visual automation to minimize Chrome browser.

Lastly, you can write batch files or bash scripts to run a sequence of TagUI scripts. So that in the scripts not involving Chrome you won't launch Chrome, but in the script when Chrome is needed then you launch Chrome.

However, the variables are not useable in between different TagUI automation scripts because they are separate sessions. You can use load or dump step to save the variables for usage in subsequent scripts.
