### ISSUE TITLE
Application Freezing When Execute Visual Automation Command

### ISSUE THREAD

**Issue by starspoint** [kelaberetiv/TagUI#563] opened 2019-09-10 10:09 UTC
Nothing show neither an error when execute the Visual Automation Command (Eg: keyboard, vision, mouse.).
![image](https://user-images.githubusercontent.com/13492875/64605404-a0850b00-d3f6-11e9-9fcd-6f2e10589ca3.png)

 The command prompt freeze there until manually terminate it. 
![image](https://user-images.githubusercontent.com/13492875/64604781-57808700-d3f5-11e9-9c27-6606d906f7bf.png)

All the log files are empty. 
Have tried running the sikulix.jar alone in the administrator mode and its working. 

I did try running the TagUI in administrator mode and disable the antivirus but try no luck

**Comment by kensoh** [comment] 2019-09-10 13:32
Hi @starspoint this error usually happens if TagUI is unable to connect to the SIkuliX process.

1. Can I check how you install TagUI? Did you download from the packaged installation in below link and choose Windows? - https://github.com/kelaberetiv/TagUI#packaged-installation

2. For Windows, if SikuliX is able to be launched successfully by TagUI, there will be a command prompt Window that shows the SikuliX process and the messages received from TagUI. Can you see such a window?

3. TagUI will only launch SikuliX engine if it detects that your script will use the visual automation and low-level keyboard / mouse control. If your script has only 1 line `live`, then TagUI will not launched SikuliX engine as it does not know that you are planning to use SikuliX in live mode. This is to speed up execution and optimise memory usage for automation workflows not requiring the engine.

**Comment by kensoh** [comment] 2019-09-10 13:34
If the issue is the live mode thingy, you can try putting some dummy step so that TagUI knows you want to use the visual automation engine. For example `hover (1,1)` or `snap page.png`.

**Comment by starspoint** [comment] 2019-09-11 01:15
Hi @kensoh , thanks for the advice, It's working now. 
I can see the third window prompting now. 
I am thinking whether could we have something (a line of text) on top to differentiate the command prompt windows for SikuliX and TagUI ?

![image](https://user-images.githubusercontent.com/13492875/64660667-0e234c80-d474-11e9-801f-236511a399aa.png)

**Comment by kensoh** [comment] 2019-09-11 01:51
That's great! Oh it will be easy to add additional line of info on top, but I cant do that. Because some users may built their own advance integrations base on the current first line of text. Changing the behaviour will break backward compatibility.

Both windows are for debugging only not for normal usage. But if you want to modify your local installation I can show you, let me know. Closing issue for now.

**Closed by kensoh** 2019-09-11 01:51 UTC
Labels: query

**Comment by starspoint** [comment] 2019-09-11 03:39
Hi @kensoh , could you please show me which file to edit ?

**Comment by kensoh** [comment] 2019-09-11 14:37
For the Chrome log window, edit src\tagui_chrome.php and add something above this line -
```
echo "[tagui] START  - listening for inputs\n\n"; while (true) {
```

For the SikuliX log window, edit src\tagui.sikuli\tagui.py and add something above this line -
```
print '[tagui] START  - listening for inputs'; print
```

**Comment by kensoh** [comment] 2019-09-11 14:39
Adding on, below are examples - 

**src\tagui_chrome.php**
```
echo "CHROME LOG WINDOW\n"
echo "[tagui] START  - listening for inputs\n\n"; while (true) {
```

**src\tagui.sikuli\tagui.py**
```
print 'SIKULIX LOG WINDOW'
print '[tagui] START  - listening for inputs'; print
```

**Comment by starspoint** [comment] 2019-09-12 01:01
Thanks @kensoh
