### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: 'rpa_python.txt'

### ISSUE THREAD

**Issue by Leeladhar13** [kelaberetiv/TagUI#925] opened 2021-02-02 18:12 UTC
Hi @kensoh ,
I have tried to run the rpa for python script and which runs for some amount time and then i am getting the following python error in Tagui Log file 

 PermissionError: [WinError 5] Access is denied: 'rpa_python.txt'

Please refer the following screenshot of the python error

![taguiErr](https://user-images.githubusercontent.com/73610755/106643737-2a1b1700-65b0-11eb-86fd-a4142b758543.PNG)

**Comment by kensoh** [comment] 2021-02-03 00:01
Hi @Leeladhar13 RPA for Python is personal side project, you can raise the issue over at https://github.com/tebelorg/RPA-Python/issues and I can look into it when I get a moment. From the screenshot, what is likely to be the cause is that the folder which you are running the automation, the user does not have the correct permissions to delete a temporary file.

Ideas to try could be checking the folder permissions, running command prompt using administrator, or change directory to that folder before running `python` command. Hopefully you can get the solution from trying out along theses ideas. I'll close the issue here for now!

**Closed by kensoh** 2021-02-03 00:01 UTC

**Comment by kensoh** [comment] 2021-02-03 00:29
Also added a video for this issue - https://www.youtube.com/watch?v=jivV4pKMQpk
