### ISSUE TITLE
Save webpage to PDF - yes directly in headless mode, or print to PDF visually

### ISSUE THREAD

**Issue by Leeladhar13** [kelaberetiv/TagUI#918] opened 2021-01-27 18:35 UTC
Hi Ken,
I am TagUI and RPA for Python user. I have an issue where i want to print web page as pdf. Is it possible to do it using RPA for python with out using visual automation ? Please give a solution for this @Ken

**Comment by kensoh** [comment] 2021-01-28 02:52
Hi @Leeladhar13, yes it is possible to save a web page as PDF without using visual automation.

Running `tagui google.tag -headless` will create a [results.pdf as attached](https://github.com/kelaberetiv/TagUI/files/5884415/results.pdf). Lemme know you run into any issues!

**google.tag**
```
https://google.com
type q as rpa[enter]
wait
snap page to results.pdf
```

For RPA for Python, it is the same way except in the [Python API syntax](https://github.com/tebelorg/RPA-Python#api-reference).

**Comment by kensoh** [comment] 2021-01-28 02:53
This only works in headless mode because Chrome by design does not allow auto-saving to PDF in the visible mode.

If you want to do it using the visible mode, then will have to use visual automation to print and save as PDF file.

**Comment by kensoh** [comment] 2021-01-28 03:24
Adding on, more details on this solution and the train of thoughts - https://www.youtube.com/watch?v=lgFaQc6PLzg

**Comment by Leeladhar13** [comment] 2021-01-28 18:50
Hi @kensoh ,
Thanks for your quick response. It's really good explanation and video helped me alot in understanding the functionaly of heedless mode for saving PDF.. 
Also can you help me with how to run RPA for python in headless mode as like TagUI?

**Comment by kensoh** [comment] 2021-01-29 17:38
Hi @Leeladhar13 you're welcome. I see, yes this can be done, here's the way to do it - https://github.com/tebelorg/RPA-Python/issues/109

**Comment by kensoh** [comment] 2021-01-29 17:39
Hi @Leeladhar13 you're welcome! Yes this can be done, here's the way to do it - https://github.com/tebelorg/RPA-Python/issues/109

**Comment by Leeladhar13** [comment] 2021-01-29 17:47
Hi @kensoh ,
Thanks for the reference. I will let you know after hacking the source file and running the same in headless mode.
Thanks alot @kensoh

**Comment by kensoh** [comment] 2021-02-18 17:44
Closing issue for now but do ping us if anything!

**Closed by kensoh** 2021-02-18 17:44 UTC
Labels: query
