### ISSUE TITLE
Issue con Mac OS installation

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#218] opened 2018-06-14 15:40 UTC
Hi @Ken,

I'm trying to install Tagui on friend's Mac : OS X El Capitan Vers 10.11.6
Tagui give us an error on a simple code like this:

```
https://www.google.com/
snap page
```

This return error: 
"LINE1] invalid URL https://www.google.com/" 
ERROR - automation aborded due to above

What could be the problem?
Thanks
Arnaud

**Comment by kensoh** [comment] 2018-06-14 16:22
Hi @adegard thanks for sharing TagUI with your friend. I can't reproduce the issue on macOS High Sierra.

```
TA:Desktop kensoh$ tagui g      

START - automation started - Fri Jun 15 2018 00:20:09 GMT+0800 (+08)
https://www.google.com/ - Google

snap page

https://www.google.com/ - Google
FINISH - automation finished - 1.2s

TA:Desktop kensoh$ cat g
https://www.google.com/
snap page
```

There is this line in tagui_parse.php which does a validation check to see if the URL provided is valid URL. It uses the PHP function filter_var below. Not sure if it is anything to do with PHP version?

```php
if (filter_var($raw_intent, FILTER_VALIDATE_URL) == false)
```

My PHP on macOS is 
```
TA:Desktop kensoh$ php --version
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by kensoh** [comment] 2018-06-14 19:23
@adegard I tried testing on PHP v5.6 and it is working too. Closing the issue for now, but if there are more clues on replicating or other users having this problem, then perhaps need to remove this PHP URL validation from the codebase.

```
olam@tebel.sg [~/api/flows]# tagui g

START - automation started - Fri Jun 15 2018 03:20:07 GMT+0800 (SGT)
https://www.google.com/ - Google

snap page

https://www.google.com/ - Google
FINISH - automation finished - 0.7s

olam@tebel.sg [~/api/flows]# php --version
PHP 5.6.36 (cli) (built: May 29 2018 01:55:39) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

CC @Aussiroth @lohvht

**Closed by kensoh** 2018-06-14 19:23 UTC
Labels: query

**Comment by adegard** [comment] 2018-06-15 13:48
OK Thank you @Ken I will check with my friend the tagui_parse.php file and see if it is enough to fix this issue.

**Comment by kensoh** [comment] 2018-06-15 16:56
Sure @adegard lemme know if you have more clues or have issues!
