### ISSUE TITLE
Issue on Windows 7 - gawk: cmd. line:2 fatal: cannot open file 

### ISSUE THREAD

**Issue by yuvrajm** [kelaberetiv/TagUI#359] opened 2019-03-21 20:38 UTC
![tagUI issue](https://user-images.githubusercontent.com/1097039/54783381-36f62200-4c47-11e9-8464-f92c45599751.PNG)
When I try to run a sample for the first instance, I get this error. The command exists with creating 3 files, namely:
1_yahoo.txt  (I guess the log file)
1_yahoo.js   (a blank file, my guess, it should produce a phantomjs script to imitate the action)
1_yahoo.raw 

```
Unable to load script C:\tagui\src\samples\1_yahoo.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

C:\tagui\src>tagui samples\\1_yahoo headless
Unable to load script C:\tagui\src\samples\1_yahoo.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

```
When I get stubborn and try again... the code exits with:
```

C:\tagui\src>tagui samples\\1_yahoo headless
Unable to load script C:\tagui\src\samples\1_yahoo.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

```

Any help will be appreciated!

**Comment by kensoh** [comment] 2019-03-22 02:50
Hi @yuvrajm have you downloaded the packaged zip file for Windows? It contains dependencies such as PHP. Haven't seen this error before but it looks potentially like an error if PHP is missing.

https://github.com/kelaberetiv/TagUI#set-up

**Comment by yuvrajm** [comment] 2019-03-22 04:36
Used windows bundle first. When it failed, used the the master bundle.
Do you think the python versions could be an issue? I got python27 and python36 both on my machine. Alternatively, should I install PHP manually first? As I recall, I did use a VertrigoServer long back on the same machinery, but to my understanding, there should not be any issue with that.

**Comment by kensoh** [comment] 2019-03-22 05:33
Should not be related to Python, because PHP is used as the execution engine. From the C:\tagui\src folder can you try typing `php\php.exe --version` to see PHP is running fine on your system? It comes with the TagUI Windows packaged zip file.

Also, if you can find another Windows laptop or desktop, try downloading and see if the same error happens. It could be some special environmental setup that was never encountered by current users.

**Comment by kensoh** [comment] 2019-03-29 15:26
Closing for the time being, pending further inputs.

**Closed by kensoh** 2019-03-29 15:26 UTC
Labels: query

**Comment by whuter** [comment] 2020-01-11 16:34
Encountered the same problem. Manually running php.exe, it prompts that MSVCR110.dll cannot be found. After installing the Microsoft Visual C++ runtime, the problem is resolved.

**Comment by kensoh** [comment] 2020-01-12 05:20
Thanks @whuter for input!

This common error is in docs under the to use section, but we are overhauling the docs to make it more user-friendly by user journey rather than by features. Also, my colleague is investigating a POC to migrate to Node.js which will remove PHP dependency for good.

**Comment by KrishJee** [comment] 2020-06-11 06:03
Had this same issue. Downloaded Visual C++ Redistributable from below and that solved my issue - 
https://tagui.readthedocs.io/en/latest/_downloads/fbf25f6118d2d4ab7642688b0da8bfa0/vcredist_x86.exe

Note - Visual C++ Redistributable 2015-2019 do not work. 2012 worked.
