### ISSUE TITLE
Fixed NullPointerException error when using TagUI MS Word present() step - done

### ISSUE THREAD

**Issue by blueberry-byte** [kelaberetiv/TagUI#1070] opened 2021-07-07 06:55 UTC
I have a series of actions that operate using screenshots. The first three actions are fine, while the 4th one always runs into a NullPointerException. It seems that the image path generated for the 4th image is missing a "/". Here is a snippet of the log I got (full path is concealed):

```
[tagui] INPUT  - [6] click TestAttachment/Images/Img_3.png
[tagui] ACTION - click TestAttachment/Images/Img_3.png
[log] CLICK on L[60,613]@S(0) (575 msec)
[tagui] OUTPUT - [6] SUCCESS

[tagui] INPUT  - [7] present TestAttachment/ImagesImg_4.png
[tagui] ACTION - present TestAttachment/ImagesImg_4.png
[error] script [ tagui ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 584, in <module>
    intent_result_value = parse_intent(tagui_intent)
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 536, in parse_intent
    return visible_intent(script_line);
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 467, in visible_intent
    if text_locator(params) == None:
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 62, in text_locator
    return findText(locator)
	at org.sikuli.script.Image.isValid(Image.java:1065)
	at org.sikuli.script.Region.wait(Region.java:2300)
	at org.sikuli.script.Region.waitText(Region.java:2752)
	at org.sikuli.script.Region.findText(Region.java:2768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NullPointerException: java.lang.NullPointerException
```

**Comment by kensoh** [comment] 2021-07-07 09:28
Hi @blueberry-byte thanks for reporting this issue!

Can you share your MS Word document file so that @ruthtxh can try to reproduce the problem?

**Comment by blueberry-byte** [comment] 2021-07-07 14:56
[TestAttachment.docx](https://github.com/kelaberetiv/TagUI/files/6778176/TestAttachment.docx)
Hi @kensoh @ruthtxh , here is the document. Thanks for your assistance!

**Comment by kensoh** [comment] 2021-07-08 02:58
Hi @blueberry-byte thanks for raising this feedback! We can replicate the problem and found a solution.

The Word plug-in syntax generation of TagUI script needs to be changed to work for functions such as present(). Otherwise the generated script reads as below which is invalid code because \ has special meaning in the JavaScript execution engine.

Ruth will be making and fix and publishing an updated Word Add-in.

```
if present('Images\Img_4.png')
```

**Comment by blueberry-byte** [comment] 2021-07-08 03:19
Thank you so much!

**Comment by kensoh** [comment] 2021-07-12 03:38
Welcome @blueberry-byte! The fix is done but we found an issue with using .csv datatable and allowing users without admin access to install the plug-in. Ruth is making the finishing touches and we'll share the download link here when it's ready (in the next couple of days). If you are working on this urgently, then you can use this plug-in first - [TagUIWordAddInSetupV3.08.zip](https://github.com/kelaberetiv/TagUI/files/6798430/TagUIWordAddInSetupV3.08.zip) (this is still WIP on the non-admin user fix, so user needs to select a folder manually some where in %APPDATA% folder)

**Comment by kensoh** [comment] 2021-07-21 03:37
Hi @blueberry-byte, the Word plug-in has been updated to work correctly with the `if present` step.

You can get the latest version from the download link on setup page - https://tagui.readthedocs.io/en/latest/setup.html

**Comment by kensoh** [comment] 2021-07-21 06:29
Thanks @blueberry-byte for confirming and closing the issue! What you reported is an important bug to be fixed.

I'll leave it open for now so that other users using older versions can know of this fix when they search for it.

**Comment by kensoh** [comment] 2022-07-15 07:50
Closing since this change has made its way into the latest packaged release.

**Closed by kensoh** 2022-07-15 07:50 UTC
Labels: bug
