### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory - pending replication checks

### ISSUE THREAD

**Issue by QuiParses** [kelaberetiv/TagUI#792] opened 2020-04-21 04:31 UTC
#### lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
```
#### uname -a
```
Linux dn00 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 \
x86_64 x86_64 x86_64 GNU/Linux
```
#### python --version
```
Python 3.7.5
```
#### php --version
```
PHP 7.3.11-0ubuntu0.19.10.4 (cli) (built: Apr  8 2020 18:58:29) ( NTS )
```
### Instructions for installation:
https://tagui.readthedocs.io/en/latest/setup.html

#### ls /usr/local/bin/ | grep tag
```
tagui
```
#### tagui /home/qih/tagui/flows/samples/1_google.tag
```
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tagui/src/tagui_chrome.php on line 34
/usr/bin/env: ‘python’: No such file or directory
```

On execution of the above 'tagui command, the Chrome Browser briefly renders an instance of the UI then crashes, with no further error message at STDOUT.

I 'rm -rf' the ~/tagui and redid the process exactly same, with the same result.

**Comment by kensoh** [comment] 2020-04-21 05:01
Hi @QuiParses are you running TagUI with the qih user?

Above error message `No such file or directory in /home/qih/tagui/src/tagui_chrome.php` is suggesting that for some reason TagUI does not have permission to create that file on your computer. Below more details, just simple writing and reading from a dummy file.

The few lines of code in tagui/src/tagui_chrome.php that trigger the error message -
```php
// initialise interface in-file before starting main loop
file_put_contents('tagui_chrome.in','');

// main loop to scan inputs from automation flow
echo "[tagui] START  - listening for inputs\n\n"; while (true) {

// scan input from run-time interface in-file
$tagui_intent = trim(file_get_contents('tagui_chrome.in'));
```

**Comment by QuiParses** [comment] 2020-04-21 05:04
Yes, the main system $usr, 'qih'. I unzipped the tagui.zip and created the dir/ & symlink as the same user so there should be no permissions issues. Also installed PHP_Latest usin 'sudo ...' too. Odd.

21 Apr 2020, 17:02 by notifications@github.com:

**Comment by kensoh** [comment] 2020-04-21 05:05
For the error message `/usr/bin/env: ‘python’: No such file or directory`, TagUI will run the command `python` if it detects that Python is used in your automation. From above 1_google.tag it does not use Python, but not sure why Python is called. You can check 2 things, try typing `python` from the same user terminal that you type tagui command to see if Python is launched. Next is check whether there is a file tagui/src/tagui_py/tagui_py.in file. There shouldn't be this file there if Python is not required in the automation script.

**Comment by kensoh** [comment] 2020-04-21 05:07
For user permissions, try doing a `chmod -R 777 /home/qih/tagui` to make all files and directories full permissions, and try running again to see if it works. If it works, that means something wrong with the permissions assigned to some of the files or folders there.

**Comment by QuiParses** [comment] 2020-04-21 05:13
Sorry for delay, redoing, testing etc.

OK: did as you said ...

$ chmod -R 777 /home/qih/tagui

qih@dn00 ~/tagui $ ll 
total 36 
drwxrwxrwx  4 qih qih  4096 Mar 10 21:37 . 
drwxr-xr-x 31 qih qih  4096 Apr 21 16:10 .. 
drwxrwxrwx  3 qih qih  4096 Mar 10 06:14 flows 
-rwxrwxrwx  1 qih qih 11343 Mar 10 06:14 LICENSE.md 
-rwxrwxrwx  1 qih qih   572 Mar 10 06:14 package.json 
-rwxrwxrwx  1 qih qih  2926 Mar 10 06:14 README.md 
drwxrwxrwx 15 qih qih  4096 Apr 21 17:09 src
$ tagui ~/tagui/flows/samples/1_google.tag
qih@dn00 ~ $ tagui ~/tagui/flows/samples/1_google.tag 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
/usr/bin/env: ‘python’: No such file or directory
If I am in ~/tagui & execute that cmd, I get the Python error again.
If I am in ~/ & execute that cmd, I get the above PHP-related error.

21 Apr 2020, 17:07 by notifications@github.com:

**Comment by kensoh** [comment] 2020-04-21 05:19
try this -

```
cd /home/qih/tagui/src
./tagui ../flows/samples/1_google.tag -n
```

If it works, it could be the way you do the symbolic link is not working and TagUI isn't launched from the correct working directory. If it doesn't work, it could be some strange behaviour on Ubuntu on running scripts and their working directory, which isn't discovered before.

**Comment by QuiParses** [comment] 2020-04-21 05:20
Went back and checked this. I have Python3 installed, so executing 'python' produces an error. Python3 gives me the Py3 REPL as expected.

qih@dn00 ~ $ cd tagui/src/tagui_py/ 
qih@dn00 ~/tagui/src/tagui_py $ ls 
tagui_py.log  tagui_py.py  tagui_py_windows.log
21 Apr 2020, 17:05 by notifications@github.com:

**Comment by kensoh** [comment] 2020-04-21 05:23
If `python` command is not available on your system, try modifying tagui\src\tagui and change the line
```
python -u tagui_py/tagui_py.py
```
to
```
python3 -u tagui_py/tagui_py.py
``` 

But don't think this is the cause of the problem, because the Google sample does not need Python at all, so it shouldn't even try to launch python command.

**Comment by QuiParses** [comment] 2020-04-21 05:24
$ cd /home/qih/tagui/src
$ pwd
/home/qih/tagui/src
./tagui ../flows/samples/1_google.tag -n
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tag
ui/src/tagui_chrome.php on line 34 
PHP Warning:  file_get_contents(tagui_chrome.in): failed to o
... continuous. Even Ctrl-C does not stop it, I have to crash the Terminal process.

21 Apr 2020, 17:20 by notifications@github.com:

**Comment by QuiParses** [comment] 2020-04-21 05:40
Progress!

qih@dn00 ~ $ tagui ~/tagui/flows/samples/1_google.tag 
/usr/bin/env: ‘python’: No such file or directory
... but no other errors. I just checked ~/tagui/src/tagui again, and there are no other instances of 'python' as executables. So I am guessing something else is being invoked at the same time?

21 Apr 2020, 17:23 by notifications@github.com:

**Comment by kensoh** [comment] 2020-04-21 05:53
Try running this -
```
cd /home/qih/tagui/src
./end_processes
```

That command kills all TagUI-related dead processes. It could be for some reason, there is some dead TagUI processes that is messing up when you try to run `tagui` on the sample.

**Comment by QuiParses** [comment] 2020-04-21 06:04
OK did that, still not working as per spec.

I have redone it all again twice, and then implemented your suggestions, with the same result.

Just now:

qih@dn00 ~ $ sudo ln -sf /home/qih/tagui/src/tagui /usr/local/bin/tagui 
qih@dn00 ~ $ cd /home/qih/tagui/src 
qih@dn00 ~/tagui/src $ ./end_processes 
qih@dn00 ~/tagui/src $ ls 
casperjs           media      tagui_chrome.php  tagui_helper.php   tagui.sikuli 
chrome             phantomjs  tagui.cmd         tagui_parse.php    test 
end_processes      samples    tagui_config.txt  tagui_py           translate.php 
end_processes.cmd  sikulix    tagui_crontab     tagui_r            transpose.php 
erina              sleep.php  tagui_footer.js   tagui_report.php   ws 
erina.cmd          slimerjs   tagui_global.csv  tagui_runner.php 
languages          tagui      tagui_header.js   tagui_service.php 
qih@dn00 ~/tagui/src $ nano tagui 
qih@dn00 ~/tagui/src $ which python 
qih@dn00 ~/tagui/src $ which python3 
/usr/bin/python3 
qih@dn00 ~/tagui/src $ cd /home/qih/tagui/src 
qih@dn00 ~/tagui/src $ ./tagui ../flows/samples/1_google.tag -n 
/usr/bin/env: ‘python’: No such file or directory
21 Apr 2020, 17:53 by notifications@github.com:

**Comment by QuiParses** [comment] 2020-04-21 07:33
Deleted tagui*; reboot, cp & unzip Tagui*.zip

Modify ~/tagui/src/tagui
--
python -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
# python3 -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
--
$ cd /home/qih/tagui/src
$ ./tagui ../flows/samples/1_google.tag -n
/usr/bin/env: ‘python’: No such file or directory

# Execute the command directly
$ python3 -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
[2] 7040

# End Processes
$ ./end_processes
$ ./tagui ../flows/samples/1_google.tag -n
/usr/bin/env: ‘python’: No such file or directory

I also went through the ~/tagui/flow/samples* 1 by 1, to verify that there was no Python call hidden in there, which of course there was not. It is acting as if it does not see Python3?

**Comment by QuiParses** [comment] 2020-04-21 07:55
### Progress
Modify ~/tagui/src/tagui
```
# chrome_command="google-chrome"
chrome_command="google-chrome-stable"
```
```
# python -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
/usr/bin/python3 -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
```
### Execute
```
$ ./tagui ../flows/samples/1_google.tag  // Removed '-n' switch
PHP Warning:  file_get_contents(tagui_chrome.in): failed to open stream: No such file or directory in /home/qih/tagui/src/tagui_chrome.php on line 34
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by kensoh** [comment] 2020-04-21 16:41
Hi @QuiParses thanks for all the troubleshooting details and logs!

I've looked through your details carefully, and I'm afraid I have no idea why above bizarre error is happening. Since you have already changed the Python command to python3 and you still get the python not found error.

I'm assuming that you are running a real Linux and not a Linux shell within Windows. If so, can you try look for another computer with Linux that you can try to see if the same error happens? Maybe your personal laptop or borrow your colleague or friend laptop.

If the other computer you cannot replicate the error, then compare the OS settings between the 2 computers to figure out what could be the cause of the problem. I'm recommending you try another laptop as you have already traced very deeply and looking further in this track is likely to waste your time without any new clues.

**Comment by kensoh** [comment] 2020-04-21 16:44
Also, I have not received any report of such an error by any TagUI user (there are over 1k users using it on Linux), so there isn't more data points from my experience what could have caused this bizarre error.

Since the TagUI source code is the same, but error is only happening on your laptop, I suspect that the more likely reason is some unique OS or environment configuration that is the root cause.

**Comment by QuiParses** [comment] 2020-04-22 02:17
Thanks for the update. I am using Kubuntu on a Desktop Machine but with a 'standard' install. I even went as far as to disable ~/.bash_aliases in case one of the Python aliases was causing an issue. 

I am planning to wipe this HDD and reinstall anyway, plus I will configure Tagui on one of my Raspberry Pi as an extra test. Thanks for all your help & patience.

**Comment by kensoh** [comment] 2020-04-22 18:28
You're welcome @QuiParses, hope there is some good results soon!

I'll close this issue for the time being, pending further inputs from your investigation.

**Comment by QuiParses** [comment] 2020-04-25 10:06
### Follow up to Issue: /usr/bin/env: 'python': No such file or directory.

### Drastic Actions
* Say 10 'Hail Marys'
* Backup, overwrite sectors & reformat HDD
* Install Lubuntu 20.04
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
#### Install TagUI
```tagui.readthedocs.io/en/latest/setup.html```
#### Install Curl
```
sudo apt update && sudo apt install curl
```
### Results 
#### PHP
```
$ php --version
PHP 7.4.3 (cli) (built: Mar 26 2020 20:24:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```
#### Python3
```
$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
#### Execute TagUI
```
$ tagui /home/qih/tagui/flows/samples/1_google.tag
/usr/bin/env: ‘python’: No such file or directory
```
### Reoccurence of original issue
#### Modify ~/tagui/src/tagui
```
# Python (2)
# python -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
# Python (3)
python -u tagui_py/tagui_py.py >> tagui_py/tagui_py.log 2>&1 &
```
#### Execute TagUI
```
$ tagui /home/qih/tagui/flows/samples/1_google.tag
/usr/bin/env: ‘python’: No such file or directory
```
Logic dictates that there must be other references to 'python' within the codebase that are getting called and causing this error
#### Search Tagui codebase
```
$ grep -r /usr/bin/env * | grep python
src/casperjs/tests/clitests/runtests.py:#!/usr/bin/env python
src/casperjs/bin/casperjs:#!/usr/bin/env python
src/slimerjs/slimerjs.py:#!/usr/bin/env python
```
#### Remediate
In all 3 files, modify

From: ```#!/usr/bin/env python```
To: ```#!/usr/bin/env python3```
### Summary
If your GNU/Linux system uses Python 3, you must modify all instances
of 'python' to 'python3', after that, it works as per design.

**Comment by kensoh** [comment] 2020-04-25 16:22
Hi @QuiParses that is very detailed and excellent detective work you have there!

Thanks for sharing your findings. Yes the file that breaks this would be this -

```
src/casperjs/bin/casperjs
```

TagUI is built on CasperJS, and for the macOS / Linux environments, CasperJS uses Python as entry point to run its code. It's been 3 years since I first wrote the integration with CasperJS, and I've forgot about that when you raise the issue. I'm sorry about that.

Changing the `python` command to `python3` would work on systems where the `python` command does not exist, and yes you've found the right solution for the problem 👏🏻👏🏻

I'll close the issue for now. And see if there are more cases of such setups, then I'll update documentation or find other ways to remove this friction for such scenarios. Thanks!

**Closed by kensoh** 2020-04-25 16:22 UTC
Labels: query

**Comment by kensoh** [comment] 2020-04-25 16:29
Adding on, I suspect that instead of changing the files, symbolic linking of below -

```
/usr/local/bin/python
```

to the python3 command in your environment may also do the trick as `python` gets redirected to `python3` on your OS. Just a guess, not sure if that works. If it does, would be easier solution.

**Comment by QuiParses** [comment] 2020-04-25 21:08
Personally, if a newb to GNU/Linuxwas doing this, perhaps it might be better to be able to modify the TagUI codebase depending on Python ver 2 /3,rather than editing a system wide ENV like 'Python'.

I'll hack up a BASH/DASH script that will detect the OS.Python.ver and modify those Shebang strings. Might take a few days 8-)

**Comment by kensoh** [comment] 2020-04-26 03:08
Modifying this way is ok, it is not a system-wide environment variable. It is creating a symbolic link for `python` which does not exist. So it should not cause any impact to break any existing apps.

**Comment by pp082** [comment] 2022-04-23 03:16
@ghost, @kensoh

Thank you very much I had the same problem with my Mac M1 pro.

Python 3.9 is preinstalled. Making the change from `python` to `python3` solved it.



[**Search Tagui codebase**](https://github.com/kelaberetiv/TagUI/issues/792#issuecomment-619354990) 

```
$ cd ~/tagui
$ grep -r /usr/bin/env * | grep python # or
$ grep -r "/usr/bin/env python" *
src/casperjs/tests/clitests/runtests.py:#!/usr/bin/env python
src/casperjs/bin/casperjs:#!/usr/bin/env python
src/slimerjs/slimerjs.py:#!/usr/bin/env python
```
Remediate

In all 3 files, modify

From: #!/usr/bin/env python
To: #!/usr/bin/env python3

**Comment by kensoh** [comment] 2022-04-23 06:33
Thanks @pp082 for sharing this solution here! 😄

**Comment by vivi88888** [comment] 2023-05-15 15:02
@kensoh @pp082 @ghost It really helps me a lot!!
