### ISSUE TITLE
TagUI not working properly - user checks and replication steps

### ISSUE THREAD

**Issue by Hassan-Ali123** [kelaberetiv/TagUI#658] opened 2019-12-20 11:06 UTC
Hi team! 
I am using TagUI. But I am facing issues repeatedly. I am running a program which includes some desktop automations like clicking start menu in Win 10, clicking maximize button, etc. I reinstalled the setup and also Sikuli setup. But I am unable to do these automations. Bot is taking too much time. Please help me resolve the issue! Thanks!

**Comment by kensoh** [comment] 2019-12-20 12:17
Hi @Hassan-Ali123 try running through the steps below to see if it fixes the issue -
https://github.com/kelaberetiv/TagUI#visual-automation

After that, you can attach the log files in tagui/src/tagui.sikuli folder so that we can see if there is any error message from the SikuliX visual automation engine.

Lastly, you can try running on other colleagues computers or your personal laptop to see if it works. And then compare the environment configurations to see why your work laptop cannot work.

Copying @siowyisheng fyi.

**Comment by Hassan-Ali123** [comment] 2019-12-20 13:21
Thanks for the suggestions. I will let you know after acting upon these!

**Comment by Hassan-Ali123** [comment] 2019-12-20 14:56
Should we attach the log files manually or using code? Please guide! Thanks!

**Comment by Hassan-Ali123** [comment] 2019-12-20 15:19
I did as guided in the link you provided. But it's still taking too much time to perform desktop automation. I also checked the Registory Editor, the key named 'Prefs' is already added there. Moreover SikuliX is also installed. Some other solutions that guide me near to the problem, please? 

Thanks!

**Comment by kensoh** [comment] 2019-12-20 15:59
Yes attach 2 things -
1. your sample script to replicate problem
2. log files in tagui\src\tagui.sikuli folder

**Comment by Hassan-Ali123** [comment] 2019-12-20 16:36
[Attach_Zip.zip](https://github.com/kelaberetiv/TagUI/files/3989156/Attach_Zip.zip)
The attached zip folder contains the coded files. I checked in tagui.sikuli folder. But I didn't find any files with name as 'log'. Can you tell the filename of the file which maintains the tagui logs?

**Comment by Hassan-Ali123** [comment] 2019-12-20 17:06
Is my Python not installed properly or something else? Should I uninstall and re-install it??

**Comment by kensoh** [comment] 2019-12-20 17:07
Your code is -

```
vision click(find('C:\tagui\start_menu.PNG')
```

Follow the example in flow samples in visual automation section and see what happens  -

```
click start_menu.PNG
```

**Comment by kensoh** [comment] 2019-12-20 17:08
If it does not work, I'm not sure what is the cause of the issue, because you already check through the steps in visual automation link, make sure you have 64-bit JDK, checking `java -version` etc.

**Comment by Hassan-Ali123** [comment] 2019-12-21 03:00
Thanks for the suggestions! Ok I re check my code and configurations as you asked me!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kensoh** [comment] 2019-12-27 05:55
Closing for now pending further inputs, you can reopen whenever!

**Closed by kensoh** 2019-12-27 05:55 UTC
Labels: general

**Comment by Hassan-Ali123** [comment] 2020-01-15 12:12
Hi team!
Please reply as soon as possible. If we open or save a project in TagUI where are the configurations updated? In the files that come inside the zipped TagUI setup folder? Please guide

**Comment by Hassan-Ali123** [comment] 2020-01-15 12:16
And also that, is it compuslory to save the TagUI coded file at C:\\tagui, or we can also save it somewhere else?

**Comment by kensoh** [comment] 2020-01-17 11:55
For first question, replied here - https://github.com/kelaberetiv/TagUI/issues/470#issuecomment-574604484

For second question, any location is fine as long there is no space in the folder path name, and the folder has write access by the user.

**Comment by kensoh** [comment] 2020-01-17 12:16
CC @siowyisheng
