### ISSUE TITLE
try catch syntax

### ISSUE THREAD

**Issue by MManchukonda** [kelaberetiv/TagUI#318] opened 2018-12-01 09:51 UTC
Hi team,

I am trying to execute a script which has try & catch blocks.

try {
api https://api.github.com/
result = api_result
echo result
}
catch(e) {echo e}
above snippet is my script.

While executing script I am getting the below errors.

ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above  //due to above step it is failing.

Can anyone help me 

to run a script with try and catch block.

**Comment by Aussiroth** [comment] 2018-12-02 14:10
Hi, the issue is that TagUI will realise you are trying to use Javascript code at the try{ line in your code. However, it will not recognise that the closing } is part of the Javascript code. The main issue here is that once TagUI detects the end of Javascript code, it will pass the code as a 'block' for casperjs to execute. You can use js begin and js finish to wrap around your code, but you will not be able to run TagUI commands in TagUI script within those blocks. 

To change TagUI to handle such cases is likely not to be on our agenda, since it is very difficult to make sure we can have the produced Javascript code be correct, as well as behave as expected when executed by casperjs for a try block with both javascript and tagui code intermixed. You can still use try/catch with Javascript, but the code within must be fully written in Javascript to work correctly.

Also as a sidenote, the original motivation behind not having error catching and resolving in TagUI was that if an automation script encounters an error, it is better to abort and warn about the issue, than to continue and potentially take actions that are unintended (like clicking in and filling in wrong information on a form, etc.).

**Comment by ramu-yarru** [comment] 2018-12-03 08:40
Hi @Aussiroth, I also have a similar kind of requirement where i need to catch the exception.  In real time scenarios, when there is an error/exception, we need to perform some compensation job (reverting the steps performed till then etc.), not only simply exit the flow. To achieve this kind of behavior we should be able to catch the exception so that developer will implement the compensation job in catch block. 
I understand that we can still use try/catch with Javascript, but we can't use TagUI steps in that try/catch block. Can you suggest is there any workaround with which we can achieve try/catch functionality?

Thanks,
Ramu

**Comment by Aussiroth** [comment] 2018-12-04 14:23
Hi Ramu, I see about the need for exception handling. I will think a bit more about this, but for now I think the best way to try and handle such cases would be preemptively use checks like the present() function to check if the element can be successfully found, and if not, perform the code for the catch.

**Comment by ramu-yarru** [comment] 2018-12-04 16:53
Hi Alvin,
Thank you for the reply. Yes, currently i am handling such kind of cases using present() or visible() functions. But it is very difficult to wrap each statement within if present() block, especially when the automation flow is huge/big in terms of number of steps. Anyways, thank you very much for considering my request.

Thanks,
Ramu

**Comment by gajananpp** [comment] 2019-01-17 23:12
Hi @Aussiroth , I have implemented exception handling which allows:

```
try 
{
https://www.wikipedia.org
click //*[@id="js-link-box-en"]/strong
// following line will fail
click //*[@id="mp-topbanne"]/ul/li[8]/a
// will not be executed
click //*[@id="ca-viewsource"]/span/a
}
catch (err)
{
// print error
echo err
https://duckduckgo.com
click //*[@id="search_form_input_homepage"]
type //*[@id="search_form_input_homepage"] as wikipedia technology portal
click //*[@id="search_button_homepage"]
click //*[@id="r1-0"]/div/h2
}
click //*[@id="mw-content-text"]/div/div[4]/div[2]/div[1]/div/a/img
wait 4
```

nested try catch or using code intents like for, if inside try catch blocks works too. Let me know if i can create a PR so that code can be reviewed. Thankyou.

**Comment by kensoh** [comment] 2019-02-10 06:02
Closing this for now, but adding on, you can try the following to make it easy for such situations, where flow_present is a normal TagUI script with the steps to be done if the element is present, and flow_missing is the script of steps to be done if the element is missing. For some complex use cases, this can make the main script more readable and easier to maintain.

```
if present('identifier')
{
    tagui flow_present
}
else
{
    tagui flow_missing
}
```


```
if present('identifier')
    tagui flow_present
else
    tagui flow_missing
```

**Closed by kensoh** 2019-02-10 06:02 UTC
Labels: query
