### ISSUE TITLE
failed to select the dropdown value using visible text (option value is used as key)

### ISSUE THREAD

**Issue by kurawadiprasanna** [kelaberetiv/TagUI#377] opened 2019-04-02 05:41 UTC
@kensoh , i am trying to select the dropdown value by text. it is not working. It works only with option "value".

Please suggest

**Comment by kensoh** [comment] 2019-04-02 19:01
Yes that is by design, and in the cheat sheet fo select step, as value is an identifier of dropdown options. You can modify src\\tagui_header.js --> casper.selectOptionByValue but that is not recommended.

Also, enabling both text and value will lead to unpredictable automation outcomes, so implementation for CasperJS uses option value. Which can be inspected from browser web inspector.

**Comment by kensoh** [comment] 2019-04-04 12:59
Closing until further inputs as using dropdown option value instead of text is by design. By want to add that if you are using visual automation, you can use `select dropdown_time.png as dropdown_option.png` to visually select the item by the displayed text.

**Closed by kensoh** 2019-04-04 12:59 UTC
Labels: query
